const period = {1 : "ⅠA", 2 : "ⅡA", 3 : "ⅢB", 4 : "ⅣB", 5 : 'ⅤB', 6 : "ⅥB", 7 : "ⅦB", 8 : "ⅧB", 9 : "ⅧB", 10 : "ⅧB", 11 : "ⅠB",
                12 : "ⅡB", 13 : "ⅢA", 14 : "ⅣA", 15 : "ⅤA", 16 : "ⅥA", 17 : "ⅦA", 18 : "ⅧA"
}

const category = {
"noble gas" :{vi : "Khí hiếm", detail : "Khí hiếm là các nguyên tố thuộc Nhóm khí hiếm, có lớp electron ngoài cùng bão hòa nên rất trơ, tồn tại dạng khí đơn nguyên tử, không màu, không mùi và có nhiệt độ sôi thấp."},
"nonmetal" : {vi : "Phi kim", detail : "Phi kim là các nguyên tố có xu hướng nhận electron để tạo ion âm, thường không dẫn điện, không dẫn nhiệt tốt, có nhiệt độ nóng chảy thấp, không dẻo, dễ gãy và thường tồn tại ở trạng thái khí hoặc rắn trong tự nhiên."},
"alkali metal" : {vi : "Kim loại kiềm", detail : "Kim loại kiềm là các nguyên tố thuộc nhóm IA, có 1 electron lớp ngoài cùng nên rất dễ nhường electron, phản ứng mạnh với nước, mềm, nhẹ và có nhiệt độ nóng chảy thấp."},
"alkaline earth metal" : {vi : "Kim loại kiềm thổ", detail : "Kim loại kiềm thổ là các nguyên tố thuộc nhóm IIA, có 2 electron lớp ngoài cùng nên dễ nhường electron, hoạt động hóa học mạnh (nhưng kém kim loại kiềm), cứng hơn và có nhiệt độ nóng chảy cao hơn."},
"metalloid" : {vi : "Á kim", detail : "Á kim là các nguyên tố có tính chất trung gian giữa kim loại và phi kim. Chúng có thể vừa dẫn điện kém như phi kim, vừa có độ dẫn điện nhất định như kim loại (bán dẫn). Á kim thường có vẻ ngoài giống kim loại nhưng giòn, không dẻo và thường tham gia phản ứng bằng cách tạo liên kết cộng hóa trị."},
"post-transition metal" : {vi : "Kim loại hậu chuyển tiếp", detail : "Kim loại hậu chuyển tiếp là các kim loại nằm sau dãy kim loại chuyển tiếp trong bảng tuần hoàn. Chúng thường mềm, nhiệt độ nóng chảy thấp hơn, dẫn điện kém hơn kim loại chuyển tiếp và có xu hướng tạo liên kết cộng hoá trị nhiều hơn trong hợp chất."},
"halogen" : {vi : "Halogen", detail : "Halogen là các nguyên tố thuộc nhóm VIIA (nhóm 17), có 7 electron lớp ngoài cùng nên dễ nhận 1 electron để tạo ion âm. Chúng là phi kim hoạt động hóa học mạnh, có tính oxi hóa mạnh, thường tồn tại dạng phân tử hai nguyên tử (X₂), độc và phản ứng mạnh với kim loại tạo muối."},
"transition metal": {vi: "Kim loại chuyển tiếp", detail: "Kim loại chuyển tiếp là các nguyên tố thuộc khối d trong bảng tuần hoàn (nhóm 3–12), có electron ở phân lớp d chưa bão hòa. Chúng thường có nhiều số oxi hóa, dẫn điện và dẫn nhiệt tốt, có độ cứng cao, nhiệt độ nóng chảy lớn và thường tạo hợp chất có màu."},
"lanthanides": {vi: "Họ Lantan", detail: "Họ Lantan là các nguyên tố thuộc dãy nguyên tố đất hiếm (từ La đến Lu), nằm ở khối f của bảng tuần hoàn. Chúng có tính chất hóa học khá giống nhau, thường có số oxi hóa +3, là kim loại mềm, màu bạc, dẫn điện tốt và dễ bị oxi hóa trong không khí. Các nguyên tố này được ứng dụng nhiều trong công nghệ cao như nam châm, màn hình, pin và vật liệu quang học."},
"actinides": {vi: "Họ Actini", detail: "Họ Actini là dãy nguyên tố từ Actinium (Ac) đến Lawrencium (Lr), thuộc khối f (5f) của bảng tuần hoàn. Hầu hết đều có tính phóng xạ, nhiều nguyên tố được tạo ra nhân tạo và có vai trò quan trọng trong năng lượng hạt nhân."}
}

const elements = {
    1 : {
    number: 1,
    row: 1,
    collum: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: 1.008,
    type: "nonmetal",
    character : "Hydrogen (H) là nguyên tố nhẹ nhất, có 1 electron và có thể vừa nhường vừa nhận electron nên thể hiện tính chất đặc biệt. Ở điều kiện thường, H tồn tại dạng khí H₂, không màu, dễ cháy và tham gia nhiều phản ứng hóa học.",
    compuond : ["H₂O", "NH₃", "HCl", "CH₄", "H₂S"],
    reaction: ["2H₂ + O₂ → 2H₂O", "H₂ + Cl₂ → 2HCl", "N₂ + 3H₂ ⇌ 2NH₃"],
    orbits: [1],
  },
  2 : {
    number: 2,
    row: 1,
    collum: 18,
    symbol: "He",
    name: "Helium",
    mass: 4.003,
    type: "noble gas",
    character : "Heli (He) là khí hiếm, có lớp electron ngoài cùng bão hòa nên rất bền. Ở điều kiện thường, He là khí không màu, không mùi, không cháy và hầu như không phản ứng hóa học. He rất nhẹ, thường dùng trong bóng bay và làm lạnh.",
    compuond : [],
    reaction: [],
    orbits: [2],
  },
  3 : {
    number: 3,
    row: 2,
    collum: 1,
    symbol: "Li",
    name: "Lithium",
    mass: 6.94,
    type: "alkali metal",
    character : "Lithium (Li) là kim loại kiềm nhẹ, có 1 electron lớp ngoài nên dễ nhường electron. Ở điều kiện thường, Li mềm, màu trắng bạc, nhẹ. Li phản ứng mạnh với nước tạo dung dịch kiềm và khí H₂, đồng thời có tính khử mạnh.",
    compuond: ["Li₂O", "LiOH", "LiCl", "Li₂CO₃", "Li₃N"],
    reaction: ["2Li + 2H₂O → 2LiOH + H₂", "4Li + O₂ → 2Li₂O", "6Li + N₂ → 2Li₃N"],
    orbits: [2, 1],
  },
  4 : {
    number: 4,
    row: 2,
    collum: 2,
    symbol: "Be",
    name: "Beryllium",
    mass: 9.012,
    type: "alkaline earth metal",
    character : "Beryli (Be) là kim loại kiềm thổ, có 2 electron lớp ngoài nên dễ nhường electron và có tính khử. Ở điều kiện thường, Be là kim loại cứng, màu xám, nhẹ nhưng giòn. Be ít phản ứng với nước ở điều kiện thường, nhưng có thể phản ứng với axit và được dùng trong hợp kim.",
    compuond : ["BeO", "Be(OH)₂", "BeCl₂", "BeSO₄", "BeCO₃"],
    reaction: ["2Be + O₂ → 2BeO", "Be + 2HCl → BeCl₂ + H₂", "Be + Cl₂ → BeCl₂"],
    orbits: [2, 2],
  },
  5 : {
    number: 5,
    row: 2,
    collum: 13,
    symbol: "B",
    name: "Boron",
    mass: 10.81,
    type: "metalloid",
    character: "Boron (B) là nguyên tố á kim, có tính chất trung gian giữa kim loại và phi kim. Nó có độ cứng cao, nhiệt độ nóng chảy lớn và thường tạo liên kết cộng hóa trị. Boron không tồn tại tự do trong tự nhiên mà thường có trong các hợp chất như borat.",
    compuond: ["B₂O₃", "H₃BO₃", "Na₂B₄O₇", "BF₃"],
    reaction: ["4B + 3O₂ → 2B₂O₃", "B₂O₃ + 3H₂O → 2H₃BO₃", "2B + 3Cl₂ → 2BCl₃"],
    orbits: [2, 3],
  },
  6 : {
    number: 6,
    row: 2,
    collum: 14,
    symbol: "C",
    name: "Carbon",
    mass: 12.01,
    type: "nonmetal",
    character: "Carbon (C) là phi kim có 4 electron lớp ngoài cùng, có khả năng tạo nhiều liên kết cộng hóa trị. Nó tồn tại ở nhiều dạng như kim cương, than chì và là nguyên tố nền tảng của hợp chất hữu cơ và sự sống.",
    compuond: ["CO", "CO₂", "CH₄", "C₆H₁₂O₆", "CaCO₃"],
    reaction: ["C + O₂ → CO₂", "2C + O₂ → 2CO", "C + 2H₂ → CH₄"],
    orbits: [2, 4],
  },
  7 : {
    number: 7,
    row: 2,
    collum: 15,
    symbol: "N",
    name: "Nitrogen",
    mass: 14.01,
    type: "nonmetal",
    character: "Nitơ (N) là phi kim có 5 electron lớp ngoài cùng, thường tạo liên kết cộng hóa trị. Ở điều kiện thường, N₂ là khí không màu, không mùi, chiếm phần lớn không khí và khá trơ về mặt hóa học.",
    compuond: ["NH₃", "NO", "NO₂", "HNO₃", "N₂O"],
    reaction: ["N₂ + 3H₂ → 2NH₃", "N₂ + O₂ → 2NO", "4NH₃ + 5O₂ → 4NO + 6H₂O"],
    orbits: [2, 5],
  },
  8 : {
    number: 8,
    row: 2,
    collum: 16,
    symbol: "O",
    name: "Oxygen",
    mass: 16.00,
    type: "nonmetal",
    character: "Oxy (O) là phi kim rất hoạt động, có 6 electron lớp ngoài cùng nên dễ nhận thêm electron. Ở điều kiện thường, O₂ là khí không màu, không mùi, cần thiết cho hô hấp và sự cháy.",
    compuond: ["H₂O", "CO₂", "O₃", "SO₂", "H₂O₂"],
    reaction: ["2H₂ + O₂ → 2H₂O", "C + O₂ → CO₂", "2Mg + O₂ → 2MgO"],
    orbits: [2, 6],
  },
  9 : {
    number: 9,
    row: 2,
    collum: 17,
    symbol: "F",
    name: "Fluorine",
    mass: 19.00,
    type: "halogen",
    character: "Flo (F) là phi kim có tính oxi hóa rất mạnh, có 7 electron lớp ngoài cùng nên dễ nhận 1 electron. Ở điều kiện thường, F₂ là khí màu vàng nhạt, rất phản ứng và độc.",
    compuond: ["HF", "CaF₂", "NaF", "SF₆"],
    reaction: ["H₂ + F₂ → 2HF", "2Na + F₂ → 2NaF"],
    orbits: [2, 7],
  },
  10 : {
    number: 10,
    row: 2,
    collum: 18,
    symbol: "Ne",
    name: "Neon",
    mass: 20.18,
    type: "noble gas",
    character: "Neon (Ne) là khí hiếm có lớp electron ngoài cùng bão hòa nên rất bền và hầu như không phản ứng hóa học. Ở điều kiện thường, Ne là khí không màu, không mùi và phát sáng đỏ cam trong đèn neon.",
    compuond: [],
    reaction: [],
    orbits: [2, 8],
  },
  11 : {
    number: 11,
    row: 3,
    collum: 1,
    symbol: "Na",
    name: "Sodium",
    mass: 22.99,
    type: "alkali metal",
    character: "Natri (Na) là kim loại kiềm, có 1 electron lớp ngoài cùng nên rất dễ nhường electron và có tính khử mạnh. Ở điều kiện thường, Na là kim loại mềm, màu trắng bạc và phản ứng rất mạnh với nước.",
    compuond: ["NaCl", "NaOH", "Na₂CO₃", "NaHCO₃"],
    reaction: ["2Na + 2H₂O → 2NaOH + H₂", "2Na + Cl₂ → 2NaCl"],
    orbits: [2, 8, 1],
  },
  12 : {
    number: 12,
    row: 3,
    collum: 2,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24.31,
    type: "alkaline earth metal",
    character: "Magie (Mg) là kim loại kiềm thổ, có 2 electron lớp ngoài cùng nên dễ nhường electron và có tính khử. Ở điều kiện thường, Mg là kim loại nhẹ, màu trắng bạc, cháy sáng trong không khí.",
    compuond: ["MgO", "MgCl₂", "Mg(OH)₂", "MgCO₃"],
    reaction: ["2Mg + O₂ → 2MgO", "Mg + 2HCl → MgCl₂ + H₂"],
    orbits: [2, 8, 2],
  },
  13 : {
    number: 13,
    row: 3,
    collum: 13,
    symbol: "Al",
    name: "Aluminum",
    mass: 26.98,
    type: "post-transition metal",
    character: "Nhôm (Al) là kim loại có 3 electron lớp ngoài cùng nên dễ nhường electron và có tính khử. Ở điều kiện thường, Al là kim loại nhẹ, màu trắng bạc, dẫn điện tốt và có lớp oxit bảo vệ nên khá bền trong không khí.",
    compuond: ["Al₂O₃", "AlCl₃", "Al(OH)₃"],
    reaction: ["4Al + 3O₂ → 2Al₂O₃", "2Al + 6HCl → 2AlCl₃ + 3H₂"],
    orbits: [2, 8, 3],
  },
  14 : {
    number: 14,
    row: 3,
    collum: 14,
    symbol: "Si",
    name: "Silicon",
    mass: 28.09,
    type: "metalloid",
    character: "Silic (Si) là á kim có 4 electron lớp ngoài cùng nên có thể tạo liên kết cộng hóa trị. Ở điều kiện thường, Si là chất rắn màu xám, cứng, là thành phần chính của cát và vật liệu bán dẫn.",
    compuond: ["SiO₂", "SiC", "H₄SiO₄", "SiCl₄", "Na₂SiO₃"],
    reaction: ["Si + O₂ → SiO₂", "Si + 2Cl₂ → SiCl₄"],
    orbits: [2, 8, 4],
  },
  15 : {
    number: 15,
    row: 3,
    collum: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 30.97,
    type: "nonmetal",
    character: "Photpho (P) là phi kim có 5 electron lớp ngoài cùng nên thường tạo liên kết cộng hóa trị. Nó tồn tại ở nhiều dạng thù hình như photpho trắng và đỏ, trong đó photpho trắng rất hoạt động và độc.",
    compuond: ["P₂O₅", "H₃PO₄", "PH₃", "Ca₃(PO₄)₂"],
    reaction: ["4P + 5O₂ → 2P₂O₅", "P₄ + 6Cl₂ → 4PCl₃"],
    orbits: [2, 8, 5],
  },
  16 : {
    number: 16,
    row: 3,
    collum: 16,
    symbol: "S",
    name: "Sulfur",
    mass: 32.06,
    type: "nonmetal",
    character: "Lưu huỳnh (S) là phi kim có 6 electron lớp ngoài cùng nên dễ nhận thêm electron. Ở điều kiện thường, S là chất rắn màu vàng, giòn và có thể cháy trong không khí.",
    compuond: ["SO₂", "SO₃", "H₂S", "H₂SO₄"],
    reaction: ["S + O₂ → SO₂", "2H₂ + S → H₂S", "2S + 3O₂ → 2SO₃"],
    orbits: [2, 8, 6],
  },
  17 : {
    number: 17,
    row: 3,
    collum: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: 35.45,
    type: "halogen",
    character: "Clo (Cl) là halogen có 7 electron lớp ngoài cùng nên dễ nhận 1 electron. Ở điều kiện thường, Cl₂ là khí màu vàng lục, mùi hắc, rất hoạt động và có tính oxi hóa mạnh.",
    compuond: ["HCl", "NaCl", "KCl", "CaCl₂"],
    reaction: ["H₂ + Cl₂ → 2HCl", "2Na + Cl₂ → 2NaCl"],
    orbits: [2, 8, 7],
  },
  18 : {
    number: 18,
    row: 3,
    collum: 18,
    symbol: "Ar",
    name: "Argon",
    mass: 39.95,
    type: "noble gas",
    character: "Argon (Ar) là khí hiếm có lớp electron ngoài cùng bão hòa nên rất bền và hầu như không phản ứng hóa học. Ở điều kiện thường, Ar là khí không màu, không mùi và chiếm một phần nhỏ trong không khí.",
    compuond: [],
    reaction: [],
    orbits: [2, 8, 8],
  },
  19 : {
    number: 19,
    row: 4,
    collum: 1,
    symbol: "K",
    name: "Potassium",
    mass: 39.10,
    type: "alkali metal",
    character: "Kali (K) là kim loại kiềm có 1 electron lớp ngoài cùng nên rất dễ nhường electron và có tính khử mạnh. Ở điều kiện thường, K là kim loại mềm, màu trắng bạc và phản ứng rất mạnh với nước.",
    compuond: ["KCl", "KOH", "K₂CO₃", "KNO₃"],
    reaction: ["2K + 2H₂O → 2KOH + H₂", "2K + Cl₂ → 2KCl"],
    orbits: [2, 8, 8, 1],
  },
  20 : {
    number: 20,
    row: 4,
    collum: 2,
    symbol: "Ca",
    name: "Calcium",
    mass: 40.08,
    type: "alkaline earth metal",
    character: "Canxi (Ca) là kim loại kiềm thổ có 2 electron lớp ngoài cùng nên dễ nhường electron và có tính khử. Ở điều kiện thường, Ca là kim loại mềm, màu trắng bạc và phản ứng với nước.",
    compuond: ["CaO", "Ca(OH)₂", "CaCO₃", "CaCl₂"],
    reaction: ["Ca + 2H₂O → Ca(OH)₂ + H₂", "2Ca + O₂ → 2CaO"],
    orbits: [2, 8, 8, 2],
  },
  21 : {
    number: 21,
    row: 4,
    collum: 3,
    symbol: "Sc",
    name: "Scandium",
    mass: 44.96,
    type: "transition metal",
    character: "Scandi (Sc) là kim loại chuyển tiếp, có nhiều số oxi hóa và thường có tính khử. Ở điều kiện thường, Sc là kim loại màu trắng bạc, nhẹ và khá bền trong không khí do có lớp oxit bảo vệ.",
    compuond: ["Sc₂O₃", "ScCl₃", "ScF₃"],
    reaction: ["4Sc + 3O₂ → 2Sc₂O₃", "2Sc + 6HCl → 2ScCl₃ + 3H₂"],
    orbits: [2, 8, 9, 2],
  },
  22 : {
    number: 22,
    row: 4,
    collum: 4,
    symbol: "Ti",
    name: "Titanium",
    mass: 47.87,
    type: "transition metal",
    character: "Titan (Ti) là kim loại chuyển tiếp bền, nhẹ và có độ cứng cao. Ở điều kiện thường, Ti có màu trắng bạc, chống ăn mòn tốt và được dùng nhiều trong hợp kim.",
    compuond: ["TiO₂", "TiCl₄", "TiN", "TiH₂"],
    reaction: ["Ti + O₂ → TiO₂", "Ti + 2Cl₂ → TiCl₄"],
    orbits: [2, 8, 10, 2],
  },
  23 : {
    number: 23,
    row: 4,
    collum: 5,
    symbol: "V",
    name: "Vanadium",
    mass: 50.94,
    type: "transition metal",
    character: "Vanadi (V) là kim loại chuyển tiếp có nhiều số oxi hóa, thường thể hiện tính khử và tạo nhiều hợp chất màu khác nhau. Ở điều kiện thường, V là kim loại cứng, màu xám bạc và khá bền.",
    compuond: ["V₂O₅", "VOCl₃", "V₂O₃", "VCl₂"],
    reaction: ["4V + 5O₂ → 2V₂O₅", "2V + 5Cl₂ → 2VCl₅"],
    orbits: [2, 8, 11, 2],
  },
  24 : {
    number: 24,
    row: 4,
    collum: 6,
    symbol: "Cr",
    name: "Chromium",
    mass: 52.00,
    type: "transition metal",
    character: "Crom (Cr) là kim loại chuyển tiếp cứng, có độ bền cao và chống ăn mòn tốt. Nó có nhiều số oxi hóa và thường được dùng để mạ kim loại và trong hợp kim thép không gỉ.",
    compuond: ["Cr₂O₃", "CrO₃", "K₂Cr₂O₇", "CrCl₃"],
    reaction: ["4Cr + 3O₂ → 2Cr₂O₃", "2Cr + 6HCl → 2CrCl₃ + 3H₂"],
    orbits: [2, 8, 13, 1],
  },
  25 : {
  number: 25,
  row: 4,
  collum: 7,
  symbol: "Mn",
  name: "Manganese",
  mass: 54.94,
  type: "transition metal",
  character: "Mangan (Mn) là kim loại chuyển tiếp có nhiều số oxi hóa, phổ biến từ +2 đến +7. Nó tham gia nhiều phản ứng oxi hóa - khử và đóng vai trò quan trọng trong luyện thép, giúp tăng độ cứng và độ bền của hợp kim.",
  compuond: ["MnO₂", "KMnO₄", "MnSO₄", "MnCl₂"],
  reaction: ["Mn + O₂ → MnO₂", "2KMnO₄ → K₂MnO₄ + MnO₂ + O₂"],
  orbits: [2, 8, 13, 2],
},
  26 : {
  number: 26,
  row: 4,
  collum: 8,
  symbol: "Fe",
  name: "Iron",
  mass: 55.85,
  type: "transition metal",
  character: "Sắt (Fe) là kim loại chuyển tiếp rất quan trọng trong tự nhiên và công nghiệp. Nó có nhiều số oxi hóa phổ biến như +2 và +3, dễ bị oxi hóa trong không khí ẩm tạo gỉ sắt. Fe là thành phần chính của thép và gang, có vai trò lớn trong xây dựng, cơ khí và sinh học (hemoglobin trong máu).",
  compuond: ["FeO", "Fe₂O₃", "Fe₃O₄", "FeCl₂"],
  reaction: ["4Fe + 3O₂ → 2Fe₂O₃", "Fe + 2HCl → FeCl₂ + H₂"],
  orbits: [2, 8, 14, 2],
},

27 : {
  number: 27,
  row: 4,
  collum: 9,
  symbol: "Co",
  name: "Cobalt",
  mass: 58.93,
  type: "transition metal",
  character: "Coban (Co) là kim loại chuyển tiếp có tính từ, thường tồn tại trong các hợp kim bền và chịu nhiệt tốt. Nó có nhiều số oxi hóa và tạo nhiều hợp chất màu khác nhau, được ứng dụng trong pin, hợp kim và vật liệu từ.",
  compuond: ["CoO", "CoCl₂", "Co₃O₄"],
  reaction: ["2Co + O₂ → 2CoO", "Co + 2HCl → CoCl₂ + H₂"],
  orbits: [2, 8, 15, 2],
},

28 : {
  number: 28,
  row: 4,
  collum: 10,
  symbol: "Ni",
  name: "Nickel",
  mass: 58.69,
  type: "transition metal",
  character: "Niken (Ni) là kim loại bền, cứng, chống ăn mòn tốt và có tính từ yếu. Nó thường được dùng trong mạ kim loại, pin và hợp kim như inox. Ni khá ổn định trong không khí và ít bị oxi hóa.",
  compuond: ["NiO", "NiCl₂", "NiSO₄"],
  reaction: ["2Ni + O₂ → 2NiO", "Ni + 2HCl → NiCl₂ + H₂"],
  orbits: [2, 8, 16, 2],
},

29 : {
  number: 29,
  row: 4,
  collum: 11,
  symbol: "Cu",
  name: "Copper",
  mass: 63.55,
  type: "transition metal",
  character: "Đồng (Cu) là kim loại dẫn điện và dẫn nhiệt rất tốt, chỉ sau bạc. Nó có màu đỏ cam đặc trưng, ít bị ăn mòn trong không khí do tạo lớp oxit bảo vệ. Cu được dùng rộng rãi trong dây điện, điện tử và hợp kim.",
  compuond: ["CuO", "CuSO₄", "CuCl₂"],
  reaction: ["2Cu + O₂ → 2CuO", "Cu + 2HCl → CuCl₂ + H₂"],
  orbits: [2, 8, 18, 1],
},

30 : {
  number: 30,
  row: 4,
  collum: 12,
  symbol: "Zn",
  name: "Zinc",
  mass: 65.38,
  type: "transition metal",
  character: "Kẽm (Zn) là kim loại có tính khử vừa phải, thường dùng để mạ sắt chống gỉ. Nó có vai trò quan trọng trong hợp kim và sinh học, đồng thời phản ứng khá dễ với axit.",
  compuond: ["ZnO", "ZnCl₂", "ZnSO₄"],
  reaction: ["Zn + 2HCl → ZnCl₂ + H₂", "2Zn + O₂ → 2ZnO"],
  orbits: [2, 8, 18, 2],
},

31 : {
  number: 31,
  row: 4,
  collum: 13,
  symbol: "Ga",
  name: "Gallium",
  mass: 69.72,
  type: "post-transition metal",
  character: "Gallium (Ga) là kim loại mềm, có nhiệt độ nóng chảy thấp, có thể tan chảy trong tay người. Nó được ứng dụng trong công nghệ bán dẫn, LED và vật liệu điện tử hiện đại.",
  compuond: ["Ga₂O₃", "GaCl₃", "GaAs"],
  reaction: ["4Ga + 3O₂ → 2Ga₂O₃", "2Ga + 3Cl₂ → 2GaCl₃"],
  orbits: [2, 8, 18, 3],
},

32 : {
  number: 32,
  row: 4,
  collum: 14,
  symbol: "Ge",
  name: "Germanium",
  mass: 72.63,
  type: "metalloid",
  character: "Germani (Ge) là á kim có tính chất bán dẫn quan trọng trong công nghiệp điện tử. Nó có cấu trúc tinh thể giống kim cương và được dùng trong chip, cảm biến và thiết bị quang điện.",
  compuond: ["GeO₂", "GeCl₄", "GeH₄"],
  reaction: ["Ge + O₂ → GeO₂", "Ge + 2Cl₂ → GeCl₄"],
  orbits: [2, 8, 18, 4],
},

33 : {
  number: 33,
  row: 4,
  collum: 15,
  symbol: "As",
  name: "Arsenic",
  mass: 74.92,
  type: "metalloid",
  character: "Asen (As) là á kim độc, có cả tính kim loại và phi kim. Nó tồn tại trong nhiều hợp chất và từng được dùng trong thuốc trừ sâu nhưng hiện nay bị hạn chế do độc tính cao.",
  compuond: ["As₂O₃", "As₂O₅", "AsH₃"],
  reaction: ["4As + 3O₂ → 2As₂O₃", "2As + 3Cl₂ → 2AsCl₃"],
  orbits: [2, 8, 18, 5],
},

34 : {
  number: 34,
  row: 4,
  collum: 16,
  symbol: "Se",
  name: "Selenium",
  mass: 78.97,
  type: "nonmetal",
  character: "Selen (Se) là phi kim có tính chất tương tự lưu huỳnh. Nó có vai trò nhỏ trong sinh học nhưng có thể độc nếu dư thừa. Se được dùng trong thủy tinh, điện tử và hợp chất quang điện.",
  compuond: ["SeO₂", "H₂Se", "SeO₃"],
  reaction: ["Se + O₂ → SeO₂", "H₂ + Se → H₂Se"],
  orbits: [2, 8, 18, 6],
},

35 : {
  number: 35,
  row: 4,
  collum: 17,
  symbol: "Br",
  name: "Bromine",
  mass: 79.90,
  type: "halogen",
  character: "Brom (Br) là halogen tồn tại ở dạng lỏng màu nâu đỏ, dễ bay hơi và có mùi mạnh. Nó có tính oxi hóa mạnh và được dùng trong hóa chất, dược phẩm và chất khử trùng.",
  compuond: ["HBr", "NaBr", "KBr"],
  reaction: ["H₂ + Br₂ → 2HBr", "2Na + Br₂ → 2NaBr"],
  orbits: [2, 8, 18, 7],
},

36 : {
  number: 36,
  row: 4,
  collum: 18,
  symbol: "Kr",
  name: "Krypton",
  mass: 83.80,
  type: "noble gas",
  character: "Krypton (Kr) là khí hiếm có lớp electron ngoài cùng bão hòa nên rất ổn định và hầu như không phản ứng hóa học. Nó được dùng trong đèn chiếu sáng và một số ứng dụng laser đặc biệt.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 8],
},
37 : {
  number: 37,
  row: 5,
  collum: 1,
  symbol: "Rb",
  name: "Rubidium",
  mass: 85.47,
  type: "alkali metal",
  character: "Rubidi (Rb) là kim loại kiềm rất hoạt động, có 1 electron lớp ngoài cùng nên dễ nhường electron và có tính khử mạnh. Nó mềm, dễ nóng chảy và phản ứng cực nhanh với nước, tạo dung dịch bazơ mạnh. Do hoạt động hóa học mạnh nên Rb không tồn tại tự do trong tự nhiên, thường gặp trong khoáng chất.",
  compuond: ["RbCl", "RbOH", "Rb₂CO₃"],
  reaction: ["2Rb + 2H₂O → 2RbOH + H₂", "2Rb + Cl₂ → 2RbCl"],
  orbits: [2, 8, 18, 8, 1],
},

38 : {
  number: 38,
  row: 5,
  collum: 2,
  symbol: "Sr",
  name: "Strontium",
  mass: 87.62,
  type: "alkaline earth metal",
  character: "Stronti (Sr) là kim loại kiềm thổ có tính hoạt động hóa học khá mạnh, dễ phản ứng với nước và không khí. Nó tạo hợp chất có màu đỏ đặc trưng trong pháo hoa. Trong tự nhiên, Sr thường tồn tại trong khoáng như celestine và strontianite.",
  compuond: ["SrO", "SrCl₂", "SrCO₃"],
  reaction: ["2Sr + O₂ → 2SrO", "Sr + 2H₂O → Sr(OH)₂ + H₂"],
  orbits: [2, 8, 18, 8, 2],
},

39 : {
  number: 39,
  row: 5,
  collum: 3,
  symbol: "Y",
  name: "Yttrium",
  mass: 88.91,
  type: "transition metal",
  character: "Ytri (Y) là kim loại chuyển tiếp tương đối bền trong không khí, thường xuất hiện trong khoáng đất hiếm. Nó có vai trò quan trọng trong vật liệu siêu dẫn, laser và gốm kỹ thuật cao.",
  compuond: ["Y₂O₃", "YCl₃", "YF₃"],
  reaction: ["4Y + 3O₂ → 2Y₂O₃", "2Y + 6HCl → 2YCl₃ + 3H₂"],
  orbits: [2, 8, 18, 9, 2],
},

40 : {
  number: 40,
  row: 5,
  collum: 4,
  symbol: "Zr",
  name: "Zirconium",
  mass: 91.22,
  type: "transition metal",
  character: "Zirconi (Zr) là kim loại có khả năng chống ăn mòn rất tốt, đặc biệt trong môi trường hóa chất và nước biển. Nó chịu nhiệt cao và được dùng trong lò phản ứng hạt nhân, hợp kim siêu bền và vật liệu công nghiệp.",
  compuond: ["ZrO₂", "ZrCl₄", "ZrH₂"],
  reaction: ["Zr + O₂ → ZrO₂", "Zr + 2Cl₂ → ZrCl₄"],
  orbits: [2, 8, 18, 10, 2],
},

41 : {
  number: 41,
  row: 5,
  collum: 5,
  symbol: "Nb",
  name: "Niobium",
  mass: 92.91,
  type: "transition metal",
  character: "Niobi (Nb) là kim loại chuyển tiếp có độ bền cơ học cao, chịu nhiệt tốt và chống ăn mòn mạnh. Nó được dùng trong hợp kim thép đặc biệt, ngành hàng không và công nghệ siêu dẫn.",
  compuond: ["Nb₂O₅", "NbCl₅", "NbC"],
  reaction: ["4Nb + 5O₂ → 2Nb₂O₅", "2Nb + 5Cl₂ → 2NbCl₅"],
  orbits: [2, 8, 18, 12, 1],
},

42 : {
  number: 42,
  row: 5,
  collum: 6,
  symbol: "Mo",
  name: "Molybdenum",
  mass: 95.95,
  type: "transition metal",
  character: "Molypden (Mo) là kim loại cứng, có nhiệt độ nóng chảy cao và độ bền lớn. Nó đóng vai trò quan trọng trong hợp kim thép, giúp tăng độ cứng và khả năng chịu nhiệt, đồng thời được dùng làm chất xúc tác trong công nghiệp hóa học.",
  compuond: ["MoO₃", "MoS₂", "MoCl₅"],
  reaction: ["2Mo + 3O₂ → 2MoO₃"],
  orbits: [2, 8, 18, 13, 1],
},

43 : {
  number: 43,
  row: 5,
  collum: 7,
  symbol: "Tc",
  name: "Technetium",
  mass: 98,
  type: "transition metal",
  character: "Techneti (Tc) là nguyên tố phóng xạ nhân tạo đầu tiên được tạo ra. Nó không có đồng vị bền và chủ yếu được dùng trong y học hạt nhân để chẩn đoán hình ảnh bên trong cơ thể.",
  compuond: ["TcO₄⁻", "Tc₂O₇"],
  reaction: ["Tc + O₂ → Tc₂O₇"],
  orbits: [2, 8, 18, 13, 2],
},

44 : {
  number: 44,
  row: 5,
  collum: 8,
  symbol: "Ru",
  name: "Ruthenium",
  mass: 101.07,
  type: "transition metal",
  character: "Rutheni (Ru) là kim loại quý thuộc nhóm bạch kim, rất bền và chống ăn mòn tốt. Nó được dùng trong điện tử, hợp kim đặc biệt và làm chất xúc tác trong phản ứng hóa học.",
  compuond: ["RuO₂", "RuCl₃"],
  reaction: ["Ru + O₂ → RuO₂"],
  orbits: [2, 8, 18, 15, 1],
},

45 : {
  number: 45,
  row: 5,
  collum: 9,
  symbol: "Rh",
  name: "Rhodium",
  mass: 102.91,
  type: "transition metal",
  character: "Rhodini (Rh) là kim loại quý hiếm, có độ phản xạ ánh sáng cao và khả năng chống ăn mòn rất mạnh. Nó được dùng trong bộ lọc khí thải ô tô, trang sức và công nghệ điện tử cao cấp.",
  compuond: ["Rh₂O₃", "RhCl₃"],
  reaction: ["4Rh + 3O₂ → 2Rh₂O₃"],
  orbits: [2, 8, 18, 16, 1],
},

46 : {
  number: 46,
  row: 5,
  collum: 10,
  symbol: "Pd",
  name: "Palladium",
  mass: 106.42,
  type: "transition metal",
  character: "Palladi (Pd) là kim loại quý có khả năng hấp thụ hydro rất tốt và hoạt động như chất xúc tác mạnh. Nó được dùng trong công nghiệp ô tô, hóa học hữu cơ và thiết bị điện tử.",
  compuond: ["PdCl₂", "PdO"],
  reaction: ["2Pd + O₂ → 2PdO"],
  orbits: [2, 8, 18, 18],
},

47 : {
  number: 47,
  row: 5,
  collum: 11,
  symbol: "Ag",
  name: "Silver",
  mass: 107.87,
  type: "transition metal",
  character: "Bạc (Ag) là kim loại có độ dẫn điện và dẫn nhiệt cao nhất trong tất cả các kim loại. Nó có ánh kim trắng sáng, ít bị ăn mòn và được sử dụng rộng rãi trong trang sức, điện tử và tiền tệ.",
  compuond: ["AgNO₃", "AgCl", "Ag₂S"],
  reaction: ["2Ag + S → Ag₂S", "2Ag + Cl₂ → 2AgCl"],
  orbits: [2, 8, 18, 18, 1],
},

48 : {
  number: 48,
  row: 5,
  collum: 12,
  symbol: "Cd",
  name: "Cadmium",
  mass: 112.41,
  type: "transition metal",
  character: "Cadmi (Cd) là kim loại mềm, độc và có tính khử khá mạnh. Nó được dùng trong pin sạc và mạ kim loại, nhưng bị hạn chế do ảnh hưởng xấu đến sức khỏe con người và môi trường.",
  compuond: ["CdS", "CdCl₂", "CdO"],
  reaction: ["2Cd + O₂ → 2CdO", "Cd + 2HCl → CdCl₂ + H₂"],
  orbits: [2, 8, 18, 18, 2],
},

49 : {
  number: 49,
  row: 5,
  collum: 13,
  symbol: "In",
  name: "Indium",
  mass: 114.82,
  type: "post-transition metal",
  character: "Indi (In) là kim loại mềm, dễ uốn và có điểm nóng chảy thấp. Nó được sử dụng trong màn hình cảm ứng, linh kiện điện tử và hợp kim đặc biệt có độ dẫn điện tốt.",
  compuond: ["In₂O₃", "InCl₃"],
  reaction: ["4In + 3O₂ → 2In₂O₃"],
  orbits: [2, 8, 18, 18, 3],
},

50 : {
  number: 50,
  row: 5,
  collum: 14,
  symbol: "Sn",
  name: "Tin",
  mass: 118.71,
  type: "post-transition metal",
  character: "Thiếc (Sn) là kim loại mềm, dễ dát mỏng và có khả năng chống ăn mòn tốt. Nó được dùng trong hợp kim hàn, tráng phủ kim loại và công nghiệp thực phẩm.",
  compuond: ["SnO", "SnO₂", "SnCl₂"],
  reaction: ["Sn + O₂ → SnO₂", "Sn + 2HCl → SnCl₂ + H₂"],
  orbits: [2, 8, 18, 18, 4],
},
51 : {
  number: 51,
  row: 5,
  collum: 15,
  symbol: "Sb",
  name: "Antimony",
  mass: 121.76,
  type: "metalloid",
  character: "Antimon (Sb) là á kim có tính chất trung gian giữa kim loại và phi kim. Nó có thể thể hiện cả tính kim loại và phi kim trong các phản ứng hóa học. Sb được dùng nhiều trong hợp kim để tăng độ cứng, trong công nghiệp điện tử và vật liệu chống cháy.",
  compuond: ["Sb₂O₃", "SbCl₃", "NaSbO₃"],
  reaction: ["4Sb + 3O₂ → 2Sb₂O₃"],
  orbits: [2, 8, 18, 18, 5],
},

52 : {
  number: 52,
  row: 5,
  collum: 16,
  symbol: "Te",
  name: "Tellurium",
  mass: 127.60,
  type: "metalloid",
  character: "Telua (Te) là á kim hiếm có tính chất gần phi kim hơn kim loại. Nó có tính dẫn điện yếu và được dùng trong hợp kim, pin mặt trời và công nghệ bán dẫn. Te khá hiếm trong tự nhiên và thường đi kèm với kim loại khác.",
  compuond: ["TeO₂", "H₂Te", "Na₂Te"],
  reaction: ["Te + O₂ → TeO₂"],
  orbits: [2, 8, 18, 18, 6],
},

53 : {
  number: 53,
  row: 5,
  collum: 17,
  symbol: "I",
  name: "Iodine",
  mass: 126.90,
  type: "halogen",
  character: "Iot (I) là halogen rắn màu tím đen, dễ thăng hoa tạo hơi màu tím đặc trưng. Nó có tính oxi hóa vừa phải và đóng vai trò quan trọng trong cơ thể người, đặc biệt là tuyến giáp. Iodine còn được dùng trong sát trùng và y học.",
  compuond: ["HI", "KI", "I₂O₅"],
  reaction: ["H₂ + I₂ → 2HI"],
  orbits: [2, 8, 18, 18, 7],
},

54 : {
  number: 54,
  row: 5,
  collum: 18,
  symbol: "Xe",
  name: "Xenon",
  mass: 131.29,
  type: "noble gas",
  character: "Xenon (Xe) là khí hiếm có lớp electron ngoài cùng bão hòa nên rất ổn định và ít phản ứng. Tuy nhiên trong điều kiện đặc biệt, nó có thể tạo một số hợp chất. Xe được dùng trong đèn chiếu sáng, đèn flash và công nghệ laser.",
  compuond: ["XeF₂", "XeF₄", "XeO₃"],
  reaction: ["Xe + F₂ → XeF₂"],
  orbits: [2, 8, 18, 18, 8],
},
55 : {
  number: 55,
  row: 6,
  collum: 1,
  symbol: "Cs",
  name: "Cesium",
  mass: 132.91,
  type: "alkali metal",
  character: "Xesi (Cs) là kim loại kiềm rất hoạt động, có 1 electron lớp ngoài nên dễ mất electron và có tính khử rất mạnh. Nó mềm, dễ nóng chảy và phản ứng cực nhanh với nước tạo dung dịch bazơ mạnh và khí hydro. Cs không tồn tại tự do trong tự nhiên và được dùng trong đồng hồ nguyên tử và các thiết bị đo thời gian chính xác cao.",
  compuond: ["CsCl", "CsOH", "Cs₂CO₃"],
  reaction: ["2Cs + 2H₂O → 2CsOH + H₂"],
  orbits: [2, 8, 18, 32, 18, 8, 1],
},

56 : {
  number: 56,
  row: 6,
  collum: 2,
  symbol: "Ba",
  name: "Barium",
  mass: 137.33,
  type: "alkaline earth metal",
  character: "Bari (Ba) là kim loại kiềm thổ có tính hoạt động hóa học khá mạnh, dễ phản ứng với nước và axit. Các hợp chất của Ba được ứng dụng trong y tế như BaSO₄ dùng chụp X-quang hệ tiêu hóa vì không tan và không độc. Ngoài ra, bari còn dùng trong pháo hoa tạo màu xanh lục đặc trưng.",
  compuond: ["BaSO₄", "BaCl₂", "BaCO₃"],
  reaction: ["Ba + 2H₂O → Ba(OH)₂ + H₂"],
  orbits: [2, 8, 18, 32, 18, 8, 2],
},

72 : {
  number: 72,
  row: 6,
  collum: 4,
  symbol: "Hf",
  name: "Hafnium",
  mass: 178.49,
  type: "transition metal",
  character: "Hafni (Hf) là kim loại chuyển tiếp có khả năng chống ăn mòn rất tốt và chịu nhiệt cao. Nó có tính chất gần giống zirconium và thường đi kèm trong khoáng tự nhiên. Hf được dùng trong lò phản ứng hạt nhân nhờ khả năng hấp thụ neutron tốt.",
  compuond: ["HfO₂", "HfCl₄"],
  reaction: ["Hf + O₂ → HfO₂"],
  orbits: [2, 8, 18, 32, 10, 2],
},

73 : {
  number: 73,
  row: 6,
  collum: 5,
  symbol: "Ta",
  name: "Tantalum",
  mass: 180.95,
  type: "transition metal",
  character: "Tantan (Ta) là kim loại rất bền, cứng và gần như không bị ăn mòn bởi axit thường. Nó có nhiệt độ nóng chảy cao và được dùng trong tụ điện, thiết bị điện tử, y tế và công nghiệp hàng không nhờ độ ổn định hóa học cao.",
  compuond: ["Ta₂O₅", "TaCl₅"],
  reaction: ["4Ta + 5O₂ → 2Ta₂O₅"],
  orbits: [2, 8, 18, 32, 11, 2],
},

74 : {
  number: 74,
  row: 6,
  collum: 6,
  symbol: "W",
  name: "Tungsten",
  mass: 183.84,
  type: "transition metal",
  character: "Vonfram (W) là kim loại có nhiệt độ nóng chảy cao nhất trong tất cả kim loại. Nó rất cứng, bền nhiệt và ít bị ăn mòn nên được dùng trong dây tóc bóng đèn, dụng cụ cắt gọt và thiết bị chịu nhiệt cao.",
  compuond: ["WO₃", "WC"],
  reaction: ["W + O₂ → WO₃"],
  orbits: [2, 8, 18, 32, 12, 2],
},

75 : {
  number: 75,
  row: 6,
  collum: 7,
  symbol: "Re",
  name: "Rhenium",
  mass: 186.21,
  type: "transition metal",
  character: "Rheni (Re) là kim loại hiếm có độ bền nhiệt và cơ học rất cao. Nó được dùng trong hợp kim siêu bền cho động cơ máy bay phản lực và các thiết bị chịu nhiệt độ cực lớn.",
  compuond: ["Re₂O₇", "ReCl₅"],
  reaction: ["4Re + 7O₂ → 2Re₂O₇"],
  orbits: [2, 8, 18, 32, 13, 2],
},

76 : {
  number: 76,
  row: 6,
  collum: 8,
  symbol: "Os",
  name: "Osmium",
  mass: 190.23,
  type: "transition metal",
  character: "Osmi (Os) là kim loại rất nặng, có mật độ cao nhất trong các nguyên tố tự nhiên. Nó cứng, giòn và rất hiếm, thường được dùng trong hợp kim đặc biệt cần độ bền và độ cứng cực cao.",
  compuond: ["OsO₄"],
  reaction: ["Os + O₂ → OsO₄"],
  orbits: [2, 8, 18, 32, 14, 2],
},

77 : {
  number: 77,
  row: 6,
  collum: 9,
  symbol: "Ir",
  name: "Iridium",
  mass: 192.22,
  type: "transition metal",
  character: "Iridi (Ir) là kim loại quý cực kỳ bền, có khả năng chống ăn mòn gần như tuyệt đối. Nó rất ổn định trong môi trường khắc nghiệt và được dùng trong thiết bị chịu nhiệt, hợp kim công nghiệp và công nghệ cao.",
  compuond: ["IrO₂"],
  reaction: ["Ir + O₂ → IrO₂"],
  orbits: [2, 8, 18, 32, 15, 2],
},

78 : {
  number: 78,
  row: 6,
  collum: 10,
  symbol: "Pt",
  name: "Platinum",
  mass: 195.08,
  type: "transition metal",
  character: "Bạch kim (Pt) là kim loại quý hiếm, có độ bền hóa học rất cao và không bị oxi hóa trong điều kiện thường. Nó được dùng trong trang sức, xúc tác hóa học, công nghiệp ô tô và lọc khí thải.",
  compuond: ["PtCl₂", "PtO₂"],
  reaction: ["Pt + O₂ → PtO₂"],
  orbits: [2, 8, 18, 32, 17, 1],
},

79 : {
  number: 79,
  row: 6,
  collum: 11,
  symbol: "Au",
  name: "Gold",
  mass: 196.97,
  type: "transition metal",
  character: "Vàng (Au) là kim loại quý không bị oxi hóa trong điều kiện thường, có ánh kim đẹp và giá trị kinh tế cao. Nó rất dẻo, dẫn điện tốt và được dùng trong trang sức, điện tử và tài chính.",
  compuond: ["AuCl₃"],
  reaction: ["Au + Cl₂ → AuCl₃"],
  orbits: [2, 8, 18, 32, 18, 1],
},

80 : {
  number: 80,
  row: 6,
  collum: 12,
  symbol: "Hg",
  name: "Mercury",
  mass: 200.59,
  type: "transition metal",
  character: "Thủy ngân (Hg) là kim loại duy nhất ở trạng thái lỏng trong điều kiện thường. Nó độc, dễ bay hơi và từng được dùng trong nhiệt kế, áp kế và thiết bị đo nhưng hiện nay bị hạn chế vì nguy hiểm.",
  compuond: ["HgO", "HgCl₂"],
  reaction: ["2Hg + O₂ → 2HgO"],
  orbits: [2, 8, 18, 32, 18, 2],
},

81 : {
  number: 81,
  row: 6,
  collum: 13,
  symbol: "Tl",
  name: "Thallium",
  mass: 204.38,
  type: "post-transition metal",
  character: "Thali (Tl) là kim loại mềm, có tính độc cao và dễ bị oxi hóa. Nó từng được dùng trong công nghiệp nhưng hiện nay bị hạn chế do ảnh hưởng xấu đến sức khỏe con người và môi trường.",
  compuond: ["Tl₂O₃", "TlCl"],
  reaction: ["4Tl + 3O₂ → 2Tl₂O₃"],
  orbits: [2, 8, 18, 32, 18, 3],
},

82 : {
  number: 82,
  row: 6,
  collum: 14,
  symbol: "Pb",
  name: "Lead",
  mass: 207.2,
  type: "post-transition metal",
  character: "Chì (Pb) là kim loại nặng, mềm và độc, có khả năng chống ăn mòn tốt. Nó được dùng trong pin, chắn bức xạ và hợp kim công nghiệp nhưng bị kiểm soát do độc tính cao.",
  compuond: ["PbO", "PbSO₄", "PbCl₂"],
  reaction: ["Pb + O₂ → PbO"],
  orbits: [2, 8, 18, 32, 18, 4],
},

83 : {
  number: 83,
  row: 6,
  collum: 15,
  symbol: "Bi",
  name: "Bismuth",
  mass: 208.98,
  type: "post-transition metal",
  character: "Bismut (Bi) là kim loại nặng nhưng ít độc hơn nhiều kim loại khác. Nó có tính chất ổn định và khi đông đặc tạo cấu trúc tinh thể đẹp, được dùng trong dược phẩm và hợp kim dễ nóng chảy.",
  compuond: ["Bi₂O₃", "BiCl₃"],
  reaction: ["4Bi + 3O₂ → 2Bi₂O₃"],
  orbits: [2, 8, 18, 32, 18, 5],
},

84 : {
  number: 84,
  row: 6,
  collum: 16,
  symbol: "Po",
  name: "Polonium",
  mass: 209,
  type: "metalloid",
  character: "Poloni (Po) là nguyên tố phóng xạ cực mạnh, rất độc và hiếm. Nó phát ra bức xạ alpha mạnh, có thể gây tổn thương tế bào nghiêm trọng và chỉ tồn tại với lượng rất nhỏ trong tự nhiên.",
  compuond: ["PoO₂"],
  reaction: [],
  orbits: [2, 8, 18, 32, 18, 6],
},

85 : {
  number: 85,
  row: 6,
  collum: 17,
  symbol: "At",
  name: "Astatine",
  mass: 210,
  type: "halogen",
  character: "Astatin (At) là halogen phóng xạ hiếm nhất, có tính chất tương tự iot nhưng không ổn định. Nó tồn tại rất ngắn trong tự nhiên và khó nghiên cứu do tính phóng xạ mạnh.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 18, 7],
},

86 : {
  number: 86,
  row: 6,
  collum: 18,
  symbol: "Rn",
  name: "Radon",
  mass: 222,
  type: "noble gas",
  character: "Radon (Rn) là khí hiếm phóng xạ, không màu, không mùi nhưng rất nguy hiểm. Khi tích tụ trong không gian kín, nó có thể gây ung thư phổi do phát ra bức xạ alpha.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 18, 8],
},
87 : {
  number: 87,
  row: 7,
  collum: 1,
  symbol: "Fr",
  name: "Francium",
  mass: 223,
  type: "alkali metal",
  character: "Franxi (Fr) là kim loại kiềm cực kỳ hiếm và phóng xạ mạnh. Nó có tính hoạt động hóa học rất cao, dễ mất electron và phản ứng mạnh với nước, nhưng tồn tại rất ngắn nên rất khó nghiên cứu.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 18, 8, 1],
},

88 : {
  number: 88,
  row: 7,
  collum: 2,
  symbol: "Ra",
  name: "Radium",
  mass: 226,
  type: "alkaline earth metal",
  character: "Radi (Ra) là kim loại phóng xạ thuộc nhóm kiềm thổ, có khả năng phát sáng yếu trong bóng tối. Nó từng được dùng trong y học nhưng hiện nay bị hạn chế do độ nguy hiểm cao.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 18, 8, 2],
},

104 : {
  number: 104,
  row: 7,
  collum: 4,
  symbol: "Rf",
  name: "Rutherfordium",
  mass: 267,
  type: "transition metal",
  character: "Rutherfordi (Rf) là nguyên tố tổng hợp siêu nặng, không tồn tại tự nhiên và có tính phóng xạ mạnh. Nó chỉ được tạo ra trong phòng thí nghiệm để nghiên cứu vật lý hạt nhân.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 10, 2],
},

105 : {
  number: 105,
  row: 7,
  collum: 5,
  symbol: "Db",
  name: "Dubnium",
  mass: 270,
  type: "transition metal",
  character: "Dubni (Db) là nguyên tố nhân tạo, cực kỳ không bền và có thời gian sống rất ngắn. Nó chỉ tồn tại trong môi trường thí nghiệm và được dùng để nghiên cứu nguyên tố siêu nặng.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 11, 2],
},

106 : {
  number: 106,
  row: 7,
  collum: 6,
  symbol: "Sg",
  name: "Seaborgium",
  mass: 271,
  type: "transition metal",
  character: "Seaborgi (Sg) là nguyên tố tổng hợp siêu nặng, không tồn tại tự nhiên và có độ ổn định rất thấp. Nó được dùng trong nghiên cứu cấu trúc hạt nhân.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 12, 2],
},

107 : {
  number: 107,
  row: 7,
  collum: 7,
  symbol: "Bh",
  name: "Bohrium",
  mass: 270,
  type: "transition metal",
  character: "Bohri (Bh) là nguyên tố nhân tạo có tính phóng xạ mạnh và không bền. Nó chỉ được tạo ra trong máy gia tốc hạt và tồn tại trong thời gian rất ngắn.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 13, 2],
},

108 : {
  number: 108,
  row: 7,
  collum: 8,
  symbol: "Hs",
  name: "Hassium",
  mass: 277,
  type: "transition metal",
  character: "Hassi (Hs) là nguyên tố siêu nặng, nhân tạo và phóng xạ mạnh. Nó chỉ tồn tại trong phòng thí nghiệm và được nghiên cứu để hiểu tính chất kim loại nặng.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 14, 2],
},

109 : {
  number: 109,
  row: 7,
  collum: 9,
  symbol: "Mt",
  name: "Meitnerium",
  mass: 278,
  type: "transition metal",
  character: "Meitneri (Mt) là nguyên tố tổng hợp cực nặng, không tồn tại tự nhiên và có thời gian sống rất ngắn. Nó được dùng trong nghiên cứu vật lý hạt nhân.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 15, 2],
},

110 : {
  number: 110,
  row: 7,
  collum: 10,
  symbol: "Ds",
  name: "Darmstadtium",
  mass: 281,
  type: "transition metal",
  character: "Darmstadti (Ds) là nguyên tố nhân tạo siêu nặng, cực kỳ không ổn định và phân rã rất nhanh. Nó chỉ tồn tại trong thời gian rất ngắn sau khi tạo ra.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 17, 1],
},

111 : {
  number: 111,
  row: 7,
  collum: 11,
  symbol: "Rg",
  name: "Roentgenium",
  mass: 282,
  type: "transition metal",
  character: "Roentgeni (Rg) là nguyên tố tổng hợp, có tính phóng xạ mạnh và không bền. Nó chỉ được nghiên cứu trong phòng thí nghiệm hạt nhân hiện đại.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 17, 2],
},

112 : {
  number: 112,
  row: 7,
  collum: 12,
  symbol: "Cn",
  name: "Copernicium",
  mass: 285,
  type: "transition metal",
  character: "Copernici (Cn) là nguyên tố siêu nặng, nhân tạo và không ổn định. Nó có thể có tính chất giống kim loại nhưng phân rã rất nhanh sau khi tạo ra.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 2],
},

113 : {
  number: 113,
  row: 7,
  collum: 13,
  symbol: "Nh",
  name: "Nihonium",
  mass: 286,
  type: "post-transition metal",
  character: "Nihoni (Nh) là nguyên tố nhân tạo, cực kỳ không bền và chỉ tồn tại trong thời gian rất ngắn. Nó được tạo ra trong phòng thí nghiệm hiện đại.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 3],
},

114 : {
  number: 114,
  row: 7,
  collum: 14,
  symbol: "Fl",
  name: "Flerovium",
  mass: 289,
  type: "post-transition metal",
  character: "Flerovi (Fl) là nguyên tố siêu nặng, có tính phóng xạ mạnh và không ổn định. Nó chỉ tồn tại trong thời gian rất ngắn sau khi được tạo ra nhân tạo.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 4],
},

115 : {
  number: 115,
  row: 7,
  collum: 15,
  symbol: "Mc",
  name: "Moscovium",
  mass: 290,
  type: "post-transition metal",
  character: "Moscovi (Mc) là nguyên tố nhân tạo siêu nặng, không bền và phân rã nhanh. Nó chủ yếu được dùng để nghiên cứu cấu trúc hạt nhân nguyên tử.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 5],
},

116 : {
  number: 116,
  row: 7,
  collum: 16,
  symbol: "Lv",
  name: "Livermorium",
  mass: 293,
  type: "post-transition metal",
  character: "Livermori (Lv) là nguyên tố tổng hợp, phóng xạ mạnh và không ổn định. Nó được tạo ra để nghiên cứu tính chất của các nguyên tố siêu nặng.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 6],
},

117 : {
  number: 117,
  row: 7,
  collum: 17,
  symbol: "Ts",
  name: "Tennessine",
  mass: 294,
  type: "halogen",
  character: "Tennessin (Ts) là halogen siêu nặng, nhân tạo và rất không bền. Nó có tính chất dự đoán giống nhóm halogen nhưng chưa được nghiên cứu đầy đủ.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 7],
},

118 : {
  number: 118,
  row: 7,
  collum: 18,
  symbol: "Og",
  name: "Oganesson",
  mass: 294,
  type: "noble gas",
  character: "Oganesson (Og) là khí hiếm siêu nặng, được tạo ra nhân tạo và cực kỳ không bền. Nó có thể không hoàn toàn giống khí hiếm truyền thống do hiệu ứng vật lý lượng tử mạnh.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 18, 8],
},
57 : {
  number: 57,
  row: 1,
  collum: 1,
  symbol: "La",
  name: "Lanthanum",
  mass: 138.91,
  type: "lanthanides",
  character: "Lantan (La) là kim loại đất hiếm mở đầu dãy lantanit. Nó có tính kim loại mạnh, dễ bị oxi hóa trong không khí và phản ứng khá dễ với nước. La được dùng trong hợp kim, vật liệu quang học và pin do tính chất dẫn điện và hóa học đặc trưng của nhóm đất hiếm.",
  compuond: ["La₂O₃", "LaCl₃"],
  reaction: ["4La + 3O₂ → 2La₂O₃"],
  orbits: [2, 8, 18, 18, 9, 2],
},

58 : {
  number: 58,
  row: 1,
  collum: 2,
  symbol: "Ce",
  name: "Cerium",
  mass: 140.12,
  type: "lanthanides",
  character: "Xeri (Ce) là kim loại đất hiếm có tính oxi hóa - khử linh hoạt. Nó được dùng trong xúc tác ô tô, đánh bóng kính và vật liệu công nghiệp.",
  compuond: ["CeO₂", "CeCl₃"],
  reaction: ["4Ce + 3O₂ → 2Ce₂O₃"],
  orbits: [2, 8, 18, 19, 9, 2],
},

59 : {
  number: 59,
  row: 1,
  collum: 3,
  symbol: "Pr",
  name: "Praseodymium",
  mass: 140.91,
  type: "lanthanides",
  character: "Prazeodymi (Pr) là kim loại đất hiếm có tính từ và quang học đặc biệt. Nó được dùng trong nam châm mạnh, kính màu và vật liệu công nghệ cao.",
  compuond: ["Pr₂O₃", "PrCl₃"],
  reaction: ["4Pr + 3O₂ → 2Pr₂O₃"],
  orbits: [2, 8, 18, 21, 8, 2],
},

60 : {
  number: 60,
  row: 1,
  collum: 4,
  symbol: "Nd",
  name: "Neodymium",
  mass: 144.24,
  type: "lanthanides",
  character: "Neodymi (Nd) là kim loại đất hiếm rất quan trọng trong công nghệ hiện đại. Nó được dùng để chế tạo nam châm cực mạnh trong loa, động cơ điện và ổ cứng.",
  compuond: ["Nd₂O₃", "NdCl₃"],
  reaction: ["4Nd + 3O₂ → 2Nd₂O₃"],
  orbits: [2, 8, 18, 22, 8, 2],
},

61 : {
  number: 61,
  row: 1,
  collum: 5,
  symbol: "Pm",
  name: "Promethium",
  mass: 145,
  type: "lanthanides",
  character: "Promethi (Pm) là nguyên tố phóng xạ hiếm, không có đồng vị bền. Nó được dùng trong pin hạt nhân nhỏ và thiết bị phát năng lượng thấp.",
  compuond: ["Pm₂O₃"],
  reaction: [],
  orbits: [2, 8, 18, 23, 8, 2],
},

62 : {
  number: 62,
  row: 1,
  collum: 6,
  symbol: "Sm",
  name: "Samarium",
  mass: 150.36,
  type: "lanthanides",
  character: "Samari (Sm) là kim loại đất hiếm có tính từ mạnh, được dùng trong nam châm samarium-cobalt chịu nhiệt cao trong công nghiệp.",
  compuond: ["Sm₂O₃", "SmCl₃"],
  reaction: ["4Sm + 3O₂ → 2Sm₂O₃"],
  orbits: [2, 8, 18, 24, 8, 2],
},

63 : {
  number: 63,
  row: 1,
  collum: 7,
  symbol: "Eu",
  name: "Europium",
  mass: 151.96,
  type: "lanthanides",
  character: "Europi (Eu) là kim loại đất hiếm có khả năng phát quang mạnh. Nó được dùng trong màn hình, đèn LED và chống làm giả tiền tệ.",
  compuond: ["Eu₂O₃", "EuCl₃"],
  reaction: ["4Eu + 3O₂ → 2Eu₂O₃"],
  orbits: [2, 8, 18, 25, 8, 2],
},

64 : {
  number: 64,
  row: 1,
  collum: 8,
  symbol: "Gd",
  name: "Gadolinium",
  mass: 157.25,
  type: "lanthanides",
  character: "Gadolini (Gd) là kim loại đất hiếm có từ tính mạnh, được dùng trong y học (MRI) để tăng tương phản hình ảnh và trong công nghệ hạt nhân.",
  compuond: ["Gd₂O₃", "GdCl₃"],
  reaction: ["4Gd + 3O₂ → 2Gd₂O₃"],
  orbits: [2, 8, 18, 25, 9, 2],
},

65 : {
  number: 65,
  row: 1,
  collum: 9,
  symbol: "Tb",
  name: "Terbium",
  mass: 158.93,
  type: "lanthanides",
  character: "Terbi (Tb) là kim loại đất hiếm có tính phát quang mạnh, được dùng trong màn hình, laser và thiết bị điện tử hiện đại.",
  compuond: ["Tb₂O₃", "TbCl₃"],
  reaction: ["4Tb + 3O₂ → 2Tb₂O₃"],
  orbits: [2, 8, 18, 27, 8, 2],
},

66 : {
  number: 66,
  row: 1,
  collum: 10,
  symbol: "Dy",
  name: "Dysprosium",
  mass: 162.50,
  type: "lanthanides",
  character: "Dysprosi (Dy) là kim loại đất hiếm có khả năng chịu từ trường mạnh và nhiệt độ cao. Nó được dùng trong nam châm công suất lớn cho động cơ điện.",
  compuond: ["Dy₂O₃", "DyCl₃"],
  reaction: ["4Dy + 3O₂ → 2Dy₂O₃"],
  orbits: [2, 8, 18, 28, 8, 2],
},

67 : {
  number: 67,
  row: 1,
  collum: 11,
  symbol: "Ho",
  name: "Holmium",
  mass: 164.93,
  type: "lanthanides",
  character: "Holmi (Ho) là kim loại đất hiếm có từ tính rất mạnh, được dùng trong laser và nghiên cứu vật liệu từ tính cao cấp.",
  compuond: ["Ho₂O₃", "HoCl₃"],
  reaction: ["4Ho + 3O₂ → 2Ho₂O₃"],
  orbits: [2, 8, 18, 29, 8, 2],
},

68 : {
  number: 68,
  row: 1,
  collum: 12,
  symbol: "Er",
  name: "Erbium",
  mass: 167.26,
  type: "lanthanides",
  character: "Erbi (Er) là kim loại đất hiếm quan trọng trong công nghệ sợi quang. Nó được dùng trong truyền tín hiệu ánh sáng và laser công suất cao.",
  compuond: ["Er₂O₃", "ErCl₃"],
  reaction: ["4Er + 3O₂ → 2Er₂O₃"],
  orbits: [2, 8, 18, 30, 8, 2],
},

69 : {
  number: 69,
  row: 1,
  collum: 13,
  symbol: "Tm",
  name: "Thulium",
  mass: 168.93,
  type: "lanthanides",
  character: "Thuli (Tm) là kim loại đất hiếm rất hiếm, được dùng trong thiết bị y tế và laser đặc biệt trong nghiên cứu khoa học.",
  compuond: ["Tm₂O₃", "TmCl₃"],
  reaction: ["4Tm + 3O₂ → 2Tm₂O₃"],
  orbits: [2, 8, 18, 31, 8, 2],
},

70 : {
  number: 70,
  row: 1,
  collum: 14,
  symbol: "Yb",
  name: "Ytterbium",
  mass: 173.05,
  type: "lanthanides",
  character: "Ytterbi (Yb) là kim loại đất hiếm mềm, được dùng trong laser và nghiên cứu vật lý lượng tử hiện đại.",
  compuond: ["Yb₂O₃", "YbCl₃"],
  reaction: ["4Yb + 3O₂ → 2Yb₂O₃"],
  orbits: [2, 8, 18, 32, 8, 2],
},

71 : {
  number: 71,
  row: 1,
  collum: 15,
  symbol: "Lu",
  name: "Lutetium",
  mass: 174.97,
  type: "lanthanides",
  character: "Luteti (Lu) là kim loại đất hiếm cuối dãy, khá bền và hiếm. Nó được dùng trong y học hạt nhân và công nghệ vật liệu tiên tiến.",
  compuond: ["Lu₂O₃", "LuCl₃"],
  reaction: ["4Lu + 3O₂ → 2Lu₂O₃"],
  orbits: [2, 8, 18, 32, 9, 2],
},
89 : {
  number: 89,
  row: 2,
  collum: 1,
  symbol: "Ac",
  name: "Actinium",
  mass: 227,
  type: "actinides",
  character: "Actini (Ac) là kim loại phóng xạ, có tính hoạt động hóa học cao và dễ bị oxi hóa. Nó là nguyên tố mở đầu dãy actinide và thường được dùng trong nghiên cứu hạt nhân và nguồn phóng xạ.",
  compuond: ["Ac₂O₃"],
  reaction: ["4Ac + 3O₂ → 2Ac₂O₃"],
  orbits: [2, 8, 18, 32, 18, 9, 2],
},

90 : {
  number: 90,
  row: 2,
  collum: 2,
  symbol: "Th",
  name: "Thorium",
  mass: 232.04,
  type: "actinides",
  character: "Thori (Th) là kim loại phóng xạ có thể dùng làm nhiên liệu hạt nhân. Nó tương đối bền hơn nhiều actinide khác và được nghiên cứu trong năng lượng hạt nhân thế hệ mới.",
  compuond: ["ThO₂", "ThCl₄"],
  reaction: ["Th + O₂ → ThO₂"],
  orbits: [2, 8, 18, 32, 18, 10, 2],
},

91 : {
  number: 91,
  row: 2,
  collum: 3,
  symbol: "Pa",
  name: "Protactinium",
  mass: 231.04,
  type: "actinides",
  character: "Protactini (Pa) là kim loại phóng xạ hiếm, có tính chất hóa học phức tạp. Nó xuất hiện trong chuỗi phân rã uranium và có ứng dụng hạn chế trong nghiên cứu hạt nhân.",
  compuond: ["Pa₂O₅"],
  reaction: [],
  orbits: [2, 8, 18, 32, 20, 9, 2],
},

92 : {
  number: 92,
  row: 2,
  collum: 4,
  symbol: "U",
  name: "Uranium",
  mass: 238.03,
  type: "actinides",
  character: "Urani (U) là kim loại phóng xạ quan trọng nhất trong năng lượng hạt nhân. Nó có khả năng phân hạch tạo ra năng lượng rất lớn và được dùng trong lò phản ứng và vũ khí hạt nhân.",
  compuond: ["UO₂", "UF₆"],
  reaction: ["U + O₂ → UO₂"],
  orbits: [2, 8, 18, 32, 21, 9, 2],
},

93 : {
  number: 93,
  row: 2,
  collum: 5,
  symbol: "Np",
  name: "Neptunium",
  mass: 237,
  type: "actinides",
  character: "Neptuni (Np) là nguyên tố phóng xạ nhân tạo, có tính chất hóa học giống uranium. Nó được tạo ra trong lò phản ứng hạt nhân và dùng trong nghiên cứu năng lượng hạt nhân.",
  compuond: ["NpO₂"],
  reaction: [],
  orbits: [2, 8, 18, 32, 22, 9, 2],
},

94 : {
  number: 94,
  row: 2,
  collum: 6,
  symbol: "Pu",
  name: "Plutonium",
  mass: 244,
  type: "actinides",
  character: "Plutoni (Pu) là kim loại phóng xạ mạnh, có khả năng phân hạch và sinh ra năng lượng lớn. Nó được dùng trong nhiên liệu hạt nhân và vũ khí hạt nhân.",
  compuond: ["PuO₂"],
  reaction: [],
  orbits: [2, 8, 18, 32, 24, 8, 2],
},

95 : {
  number: 95,
  row: 2,
  collum: 7,
  symbol: "Am",
  name: "Americium",
  mass: 243,
  type: "actinides",
  character: "Americi (Am) là kim loại phóng xạ nhân tạo, thường được dùng trong thiết bị phát hiện khói và nghiên cứu hạt nhân.",
  compuond: ["AmO₂"],
  reaction: [],
  orbits: [2, 8, 18, 32, 25, 8, 2],
},

96 : {
  number: 96,
  row: 2,
  collum: 8,
  symbol: "Cm",
  name: "Curium",
  mass: 247,
  type: "actinides",
  character: "Curi (Cm) là kim loại phóng xạ mạnh, được tạo ra nhân tạo. Nó được dùng trong nghiên cứu khoa học và nguồn nhiệt cho thiết bị không gian.",
  compuond: ["CmO₂"],
  reaction: [],
  orbits: [2, 8, 18, 32, 25, 9, 2],
},

97 : {
  number: 97,
  row: 2,
  collum: 9,
  symbol: "Bk",
  name: "Berkelium",
  mass: 247,
  type: "actinides",
  character: "Berkeli (Bk) là nguyên tố nhân tạo, phóng xạ mạnh và rất hiếm. Nó chủ yếu được dùng trong nghiên cứu nguyên tố siêu nặng.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 27, 8, 2],
},

98 : {
  number: 98,
  row: 2,
  collum: 10,
  symbol: "Cf",
  name: "Californium",
  mass: 251,
  type: "actinides",
  character: "Californi (Cf) là kim loại phóng xạ mạnh, có khả năng phát neutron. Nó được dùng trong dò mìn và nghiên cứu hạt nhân.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 28, 8, 2],
},

99 : {
  number: 99,
  row: 2,
  collum: 11,
  symbol: "Es",
  name: "Einsteinium",
  mass: 252,
  type: "actinides",
  character: "Einsteini (Es) là nguyên tố nhân tạo cực hiếm, phóng xạ mạnh và chỉ tồn tại trong thời gian rất ngắn.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 29, 8, 2],
},

100 : {
  number: 100,
  row: 2,
  collum: 12,
  symbol: "Fm",
  name: "Fermium",
  mass: 257,
  type: "actinides",
  character: "Fermi (Fm) là nguyên tố phóng xạ nhân tạo, được tạo ra từ thử nghiệm hạt nhân và có thời gian sống rất ngắn.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 30, 8, 2],
},

101 : {
  number: 101,
  row: 2,
  collum: 13,
  symbol: "Md",
  name: "Mendelevium",
  mass: 258,
  type: "actinides",
  character: "Mendelevi (Md) là nguyên tố nhân tạo, phóng xạ mạnh và được dùng trong nghiên cứu hóa học nguyên tố siêu nặng.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 31, 8, 2],
},

102 : {
  number: 102,
  row: 2,
  collum: 14,
  symbol: "No",
  name: "Nobelium",
  mass: 259,
  type: "actinides",
  character: "Nobeli (No) là nguyên tố nhân tạo, rất không bền và chỉ tồn tại trong thời gian cực ngắn trong thí nghiệm.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 8, 2],
},

103 : {
  number: 103,
  row: 2,
  collum: 15,
  symbol: "Lr",
  name: "Lawrencium",
  mass: 266,
  type: "actinides",
  character: "Lawrenci (Lr) là nguyên tố tổng hợp cuối dãy actinide, phóng xạ mạnh và rất không ổn định.",
  compuond: [],
  reaction: [],
  orbits: [2, 8, 18, 32, 32, 9, 2],
},
"*" : {
    number: "*",
    row: 6,
    collum: 3,
    symbol: "",
    name: "",
    mass: "",
    type: "lanthanides",
},
"**" : {
    number: "**",
    row: 7,
    collum: 3,
    symbol: "",
    name: "",
    mass: "",
    type: "actinides",
}
}

const compoundsDetail = {
    "H₂O" : "Là hợp chất thiết yếu cho sự sống, tồn tại ở ba trạng thái rắn, lỏng, khí trong tự nhiên. Nước có khả năng hòa tan nhiều chất và tham gia vào hầu hết các quá trình sinh học và hóa học.",
    "NH₃" : "Là chất khí không màu, mùi khai đặc trưng, tan tốt trong nước tạo dung dịch bazơ yếu. Amoniac được sử dụng rộng rãi trong sản xuất phân bón và làm chất tẩy rửa",
    "HCl" : "Là dung dịch axit mạnh, có khả năng ăn mòn kim loại và nhiều vật liệu khác. HCl được sử dụng trong công nghiệp, chế biến thực phẩm và thí nghiệm hóa học.",
    "CH₄" : "Là khí không màu, không mùi, dễ cháy và là thành phần chính của khí tự nhiên. Metan được dùng làm nhiên liệu và là nguyên liệu quan trọng trong công nghiệp hóa học.", 
    "H₂S" : "Là khí không màu, mùi trứng thối đặc trưng và rất độc ở nồng độ cao. H₂S thường xuất hiện trong môi trường phân hủy hữu cơ và trong một số nguồn khí tự nhiên.",
    "Li₂O" : "Là oxit bazơ của liti, chất rắn màu trắng, phản ứng với nước tạo LiOH. Được sử dụng trong sản xuất gốm sứ và vật liệu chịu nhiệt.",
    "LiOH" : "Là bazơ mạnh, chất rắn màu trắng, tan tốt trong nước tạo dung dịch kiềm. Được dùng trong sản xuất pin, chất hấp thụ CO₂ và công nghiệp hóa học.",
    "LiCl" : "Là muối tan tốt trong nước, có tính hút ẩm mạnh. Được sử dụng trong điều hòa không khí, làm chất hút ẩm và trong công nghiệp luyện kim.",
    "Li₂CO₃" : "Là muối ít tan trong nước, chất rắn màu trắng. Được dùng trong sản xuất gốm sứ, thủy tinh và pin lithium, cũng như trong y học.",
    "Li₃N" : "Là hợp chất nitrua của liti, chất rắn màu đỏ sẫm, phản ứng với nước tạo NH₃. Được dùng trong nghiên cứu hóa học và sản xuất vật liệu đặc biệt.",
    "BeO" : "Là oxit lưỡng tính, chất rắn màu trắng, rất bền nhiệt. Có thể phản ứng với cả axit và bazơ, dùng trong vật liệu chịu nhiệt và gốm kỹ thuật cao.",
    "Be(OH)₂" : "Là hiđroxit lưỡng tính, kết tủa keo trắng, ít tan trong nước. Có thể tan trong axit và kiềm, thể hiện tính chất hóa học đặc trưng của Be.",
    "BeCl₂" : "Là muối dễ tan, có tính hút ẩm mạnh và cấu trúc cộng hoá trị. Được dùng trong tổng hợp hữu cơ và nghiên cứu hóa học.",
    "BeSO₄" : "Là muối tan trong nước, tạo dung dịch không màu. Thường dùng trong nghiên cứu hóa học và một số ứng dụng đặc biệt của Be.",
    "BeCO₃" : "Là muối không bền, ít tan trong nước, dễ bị phân huỷ thành BeO và CO₂ khi nung nóng.",
    "B₂O₃" : "Là oxit axit của bo, chất rắn dạng thủy tinh, dễ hút ẩm và phản ứng với nước tạo H₃BO₃.",
    "H₃BO₃" : "Là axit boric, axit yếu, tan ít trong nước, có tính sát khuẩn nhẹ và dùng trong công nghiệp thủy tinh.",
    "Na₂B₄O₇" : "Là natri tetraborat (borax), muối quan trọng của bo, dùng trong sản xuất thủy tinh, xà phòng và chất tẩy rửa.",    
    "BF₃" : "Là bor triflorua, khí không màu, rất độc và là axit Lewis mạnh, dùng làm xúc tác trong tổng hợp hữu cơ.",
    "CO":"Là khí cacbon monoxit, không màu, không mùi, rất độc do gắn chặt với hemoglobin trong máu, gây ngạt.",
    "CO₂":"Là khí cacbon đioxit, không màu, không cháy, tham gia hiệu ứng nhà kính và cần cho quang hợp của cây xanh.",
    "CH₄":"Là khí metan, thành phần chính của khí tự nhiên, không màu, dễ cháy và là nhiên liệu quan trọng.",
    "C₆H₁₂O₆":"Là glucozơ, đường đơn quan trọng trong sinh học, cung cấp năng lượng cho tế bào sống.",
    "CaCO₃":"Là canxi cacbonat, chất rắn phổ biến trong đá vôi, phấn và vỏ sò, dùng trong xây dựng và công nghiệp.",
    "NH₃":"Là amoniac, khí không màu, mùi khai đặc trưng, tan tốt trong nước tạo dung dịch bazơ yếu và dùng nhiều trong sản xuất phân bón.",
    "NO":"Là khí nitric oxit, không màu, dễ bị oxi hóa thành NO₂, có vai trò trong sinh học và công nghiệp hóa học.",
    "NO₂":"Là khí nitơ đioxit, màu nâu đỏ, mùi hắc, độc, tham gia gây ô nhiễm không khí và mưa axit.",
    "HNO₃":"Là axit nitric, axit mạnh, có tính oxi hóa cao, ăn mòn kim loại và được dùng trong sản xuất phân bón, thuốc nổ.",
    "N₂O":"Là khí nitơ oxit (khí cười), không màu, ít độc, có tác dụng gây mê nhẹ và dùng trong y tế, thực phẩm.",
    "H₂O":"Là nước, hợp chất thiết yếu cho sự sống, tồn tại ở ba trạng thái rắn, lỏng, khí và có khả năng hòa tan nhiều chất.",
    "CO₂":"Là khí cacbon đioxit, không màu, không cháy, góp phần vào hiệu ứng nhà kính và cần cho quá trình quang hợp.",
    "O₃":"Là ozon, dạng thù hình của oxi, có tính oxi hóa mạnh, giúp bảo vệ Trái Đất khỏi tia UV ở tầng bình lưu.",
    "SO₂":"Là khí lưu huỳnh đioxit, không màu, mùi hắc, độc, gây ô nhiễm không khí và góp phần tạo mưa axit.",
    "H₂O₂":"Là hiđro peoxit, chất lỏng không màu, có tính oxi hóa mạnh, dùng trong tẩy trắng và sát trùng.",
    "HF":"Là axit flohiđric, axit yếu nhưng rất ăn mòn, có khả năng hòa tan thủy tinh và dùng trong khắc kính, công nghiệp hóa học.",
    "CaF₂":"Là canxi florua (fluorit), chất rắn ít tan trong nước, được dùng trong sản xuất axit HF và luyện kim.",
    "NaF":"Là natri florua, chất rắn tan trong nước, được dùng trong kem đánh răng để phòng sâu răng và trong công nghiệp.",
    "SF₆":"Là lưu huỳnh hexaflorua, khí không màu, rất bền, cách điện tốt và được dùng trong thiết bị điện cao áp.",
    "NaCl":"Là natri clorua (muối ăn), chất rắn tinh thể màu trắng, tan tốt trong nước và là muối phổ biến nhất trong đời sống.",
    "NaOH":"Là natri hiđroxit, bazơ mạnh, chất rắn hút ẩm mạnh, tan trong nước tỏa nhiệt và dùng trong sản xuất xà phòng, giấy.",
    "Na₂CO₃":"Là natri cacbonat (soda), chất rắn tan trong nước tạo dung dịch bazơ yếu, dùng trong sản xuất thủy tinh và chất tẩy rửa.",
    "NaHCO₃":"Là natri hiđrocacbonat (baking soda), chất rắn ít tan, có tính bazơ yếu, dùng trong thực phẩm và chữa axit dạ dày.",
    "MgO":"Là magie oxit, chất rắn màu trắng, bền nhiệt, có tính bazơ và dùng trong vật liệu chịu lửa.",
    "MgCl₂":"Là magie clorua, muối tan trong nước, thường có trong nước biển và dùng trong công nghiệp luyện kim.",
    "Mg(OH)₂":"Là magie hiđroxit, kết tủa trắng ít tan trong nước, có tính bazơ yếu và dùng làm thuốc kháng axit.",
    "MgCO₃":"Là magie cacbonat, chất rắn màu trắng, ít tan, bị phân hủy khi nung tạo MgO và CO₂.",
    "Al₂O₃":"Là nhôm oxit, chất rắn rất bền, có tính lưỡng tính, nhiệt độ nóng chảy cao và dùng trong vật liệu chịu nhiệt, gốm kỹ thuật.",
    "AlCl₃":"Là nhôm clorua, muối dễ bay hơi và hút ẩm mạnh, thường tồn tại dạng dimer và dùng làm xúc tác trong tổng hợp hữu cơ.",
    "Al(OH)₃":"Là nhôm hiđroxit, kết tủa trắng, có tính lưỡng tính, tan trong axit và bazơ, dùng trong thuốc kháng axit và xử lý nước.",
    "SiO₂":"Là silic đioxit, chất rắn rất bền, tồn tại nhiều trong cát và thạch anh, có tính axit yếu và dùng trong thủy tinh, gốm sứ.",
    "SiC":"Là silic cacbua, chất rắn rất cứng, bền nhiệt cao, dùng làm vật liệu mài và chịu nhiệt.",
    "H₄SiO₄":"Là axit silixic, axit rất yếu, không bền, thường tồn tại trong dung dịch loãng và dễ trùng ngưng tạo gel silic.",
    "SiCl₄":"Là silic tetraclorua, chất lỏng không màu, dễ bay hơi, bị thủy phân mạnh trong nước tạo H₄SiO₄ và HCl.",
    "Na₂SiO₃":"Là natri silicat (thủy tinh lỏng), tan trong nước, có tính bazơ yếu và dùng trong sản xuất keo dán, chất tẩy rửa.",
    "P₂O₅":"Là điphotpho pentaoxit, chất rắn trắng, háo nước mạnh, là oxit axit và dùng làm chất hút ẩm.",
    "H₃PO₄":"Là axit photphoric, axit trung bình, tan tốt trong nước, dùng trong sản xuất phân bón và thực phẩm.",
    "PH₃":"Là photphin, khí không màu, rất độc, mùi khó chịu, dễ cháy và dùng trong diệt côn trùng.",
    "Ca₃(PO₄)₂":"Là canxi photphat, chất rắn ít tan, có trong xương, răng và dùng trong sản xuất phân bón.",
    "SO₂":"Là lưu huỳnh đioxit, khí không màu, mùi hắc, độc, tan trong nước tạo axit yếu và gây ô nhiễm không khí.",
    "SO₃":"Là lưu huỳnh trioxit, chất rắn hoặc lỏng không màu, phản ứng mạnh với nước tạo H₂SO₄.",
    "H₂S":"Là hiđro sunfua, khí không màu, mùi trứng thối đặc trưng, rất độc và dễ cháy.",
    "H₂SO₄":"Là axit sunfuric, axit mạnh, háo nước, có tính oxi hóa mạnh và dùng rộng rãi trong công nghiệp.",
    "HCl":"Là hiđro clorua (trong dung dịch là axit clohiđric), axit mạnh, ăn mòn và dùng nhiều trong công nghiệp và thí nghiệm.",
    "NaCl":"Là natri clorua (muối ăn), chất rắn tinh thể trắng, tan tốt trong nước và rất phổ biến trong đời sống.",
    "KCl":"Là kali clorua, muối tan trong nước, dùng làm phân bón và bổ sung kali trong nông nghiệp.",
    "CaCl₂":"Là canxi clorua, muối tan mạnh trong nước, có tính hút ẩm và dùng làm chất hút ẩm, chống đóng băng.",
    "KCl":"Là kali clorua, muối tinh thể trắng, tan tốt trong nước và dùng chủ yếu làm phân bón cung cấp kali.",
    "KOH":"Là kali hiđroxit, bazơ mạnh, chất rắn hút ẩm mạnh, tan trong nước tỏa nhiệt và dùng trong sản xuất xà phòng, hóa chất.",
    "K₂CO₃":"Là kali cacbonat, chất rắn tan trong nước tạo dung dịch bazơ yếu, dùng trong sản xuất thủy tinh và chất tẩy rửa.",
    "KNO₃":"Là kali nitrat, chất rắn tan tốt trong nước, có tính oxi hóa và dùng trong phân bón, pháo hoa.",
    "CaO":"Là canxi oxit (vôi sống), chất rắn màu trắng, có tính bazơ mạnh, phản ứng mạnh với nước tỏa nhiệt tạo Ca(OH)₂.",
    "Ca(OH)₂":"Là canxi hiđroxit (nước vôi trong), bazơ yếu, ít tan trong nước, dùng trong xây dựng và xử lý nước.",
    "CaCO₃":"Là canxi cacbonat, chất rắn phổ biến trong đá vôi, phấn, vỏ sò, dùng trong xây dựng và công nghiệp.",
    "CaCl₂":"Là canxi clorua, muối tan tốt trong nước, có tính hút ẩm mạnh và dùng làm chất hút ẩm, chống đóng băng.", 
    "Sc₂O₃":"Là scandium oxit, chất rắn màu trắng, bền nhiệt, có tính bazơ yếu và dùng trong vật liệu gốm, hợp kim đặc biệt.",
    "ScCl₃":"Là scandium clorua, muối rắn dễ tan trong nước, dùng trong tổng hợp hóa học và nghiên cứu vật liệu.",
    "ScF₃":"Là scandium florua, chất rắn ít tan, bền nhiệt và có cấu trúc ion, dùng trong luyện kim và nghiên cứu.",    
    "TiO₂":"Là titan đioxit, chất rắn màu trắng, bền hóa học, không độc, dùng nhiều trong sơn, nhựa và mỹ phẩm làm chất tạo màu trắng.",
    "TiCl₄":"Là titan tetraclorua, chất lỏng không màu, bốc khói mạnh trong không khí do bị thủy phân, dùng trong sản xuất titan kim loại.",
    "TiN":"Là titan nitrua, chất rắn màu vàng kim, rất cứng, bền nhiệt, dùng làm lớp phủ bảo vệ dụng cụ cắt.",
    "TiH₂":"Là titan hiđrua, chất rắn, không bền trong điều kiện thường, dễ phân hủy và dùng trong nghiên cứu vật liệu.",
    "V₂O₅":"Là vanadi pentaoxit, chất rắn màu vàng cam, có tính oxi hóa mạnh và dùng làm xúc tác trong sản xuất H₂SO₄.",
    "VOCl₃":"Là vanadi oxit clorua, chất lỏng màu vàng, dễ bay hơi và bị thủy phân mạnh trong nước.",
    "V₂O₃":"Là vanadi(III) oxit, chất rắn màu đen, có tính khử và dùng trong nghiên cứu vật liệu.",
    "VCl₂":"Là vanadi(II) clorua, chất rắn màu tím, có tính khử mạnh và dễ bị oxi hóa trong không khí.",
    "Cr₂O₃":"Là crom(III) oxit, chất rắn màu xanh lục, bền nhiệt, có tính lưỡng tính yếu và dùng làm chất tạo màu trong gốm, sơn.",
    "CrO₃":"Là crom(VI) oxit, chất rắn màu đỏ sẫm, có tính oxi hóa rất mạnh và là chất độc, dùng trong mạ điện và tổng hợp hóa học.",
    "K₂Cr₂O₇":"Là kali đicromat, chất rắn màu da cam, có tính oxi hóa mạnh và dùng trong phòng thí nghiệm, thuộc da và công nghiệp.",
    "CrCl₃":"Là crom(III) clorua, chất rắn màu tím lục, tan trong nước và dùng trong tổng hợp hóa học và mạ kim loại.", 
    "MnO₂":"Là mangan đioxit, chất rắn màu đen, bền trong điều kiện thường, có tính oxi hóa và thường được dùng làm chất xúc tác trong phản ứng phân hủy H₂O₂ và trong pin khô.",
    "KMnO₄":"Là kali pemanganat, chất rắn màu tím đậm, có tính oxi hóa rất mạnh, dễ tham gia phản ứng oxi hóa-khử và được dùng trong sát trùng, xử lý nước và chuẩn độ.",
    "MnSO₄":"Là mangan(II) sunfat, muối tinh thể màu hồng nhạt, tan trong nước, cung cấp ion Mn²⁺ và được dùng trong phân bón và tổng hợp hóa học.",
    "FeO":"Là sắt(II) oxit, chất rắn màu đen, có tính bazơ yếu, dễ bị oxi hóa trong không khí thành Fe₂O₃.",
    "Fe₂O₃":"Là sắt(III) oxit, chất rắn màu nâu đỏ, là thành phần chính của gỉ sắt, bền và được dùng làm chất màu trong sơn và vật liệu.",
    "Fe₃O₄":"Là oxit sắt từ, chất rắn màu đen, có từ tính mạnh, tồn tại tự nhiên dưới dạng magnetit và có tính chất trung gian giữa FeO và Fe₂O₃.",
    "FeCl₂":"Là sắt(II) clorua, muối màu xanh lục nhạt, tan trong nước nhưng dễ bị oxi hóa thành FeCl₃ trong không khí.",
    "CoO":"Là coban(II) oxit, chất rắn màu xám xanh, có tính bazơ yếu và được dùng trong sản xuất gốm và chất màu.",
    "CoCl₂":"Là coban(II) clorua, chất rắn màu xanh lam, có khả năng đổi màu theo độ ẩm nên được dùng làm chất chỉ thị độ ẩm.",
    "Co₃O₄":"Là oxit hỗn hợp của coban, chất rắn màu đen, có tính oxi hóa và được dùng làm chất xúc tác trong công nghiệp.",
    "NiO":"Là niken oxit, chất rắn màu xanh lục, có tính bazơ yếu, dùng trong gốm sứ, pin và hợp kim.",
    "NiCl₂":"Là niken clorua, muối màu xanh lục, tan trong nước, thường dùng trong mạ điện và tổng hợp hóa học.",
    "NiSO₄":"Là niken sunfat, muối tinh thể màu xanh, tan trong nước và dùng nhiều trong công nghiệp mạ niken và pin.",
    "CuO":"Là đồng(II) oxit, chất rắn màu đen, có tính oxi hóa yếu, dùng trong gốm, thủy tinh và tổng hợp hóa học.",
    "CuSO₄":"Là đồng(II) sunfat, tinh thể màu xanh lam, tan trong nước, có tính diệt nấm và dùng trong mạ điện.",
    "CuCl₂":"Là đồng(II) clorua, muối màu xanh lục, tan tốt trong nước và tham gia nhiều phản ứng hóa học trong phòng thí nghiệm.",
    "ZnO":"Là kẽm oxit, chất rắn màu trắng, không tan trong nước, có tính lưỡng tính và dùng trong kem chống nắng, cao su và dược phẩm.",
    "ZnCl₂":"Là kẽm clorua, muối hút ẩm mạnh, tan trong nước và được dùng trong công nghiệp luyện kim và hóa chất.",
    "ZnSO₄":"Là kẽm sunfat, muối tinh thể trắng, tan trong nước và được dùng để bổ sung kẽm trong nông nghiệp và y học.",
    "Ga₂O₃":"Là gali oxit, chất rắn màu trắng, bền nhiệt và có ứng dụng quan trọng trong vật liệu bán dẫn công suất cao.",
    "GaCl₃":"Là gali clorua, chất rắn dễ bay hơi, bị thủy phân mạnh trong nước và dùng trong tổng hợp hữu cơ và công nghệ bán dẫn.",
    "GaAs":"Là gali arsenua, vật liệu bán dẫn quan trọng, có hiệu suất cao trong thiết bị điện tử, laser và vi mạch tốc độ cao.",
    "GeO₂":"Là germani đioxit, chất rắn màu trắng, có tính axit yếu và được dùng trong quang học và chất bán dẫn.",
    "GeCl₄":"Là germani tetraclorua, chất lỏng không màu, dễ bay hơi, bị thủy phân mạnh tạo H₄GeO₄ và HCl.",
    "GeH₄":"Là germani hiđrua, khí không bền, dễ phân hủy và rất độc.",
    "As₂O₃":"Là asen(III) oxit, chất rắn màu trắng, rất độc, có tính oxi hóa và được dùng trong hóa học đặc biệt.",
    "As₂O₅":"Là asen(V) oxit, chất rắn màu trắng, có tính axit và oxi hóa mạnh hơn As₂O₃.",
    "AsH₃":"Là arsine, khí không màu, cực độc, có mùi tỏi và dễ phân hủy khi đun nóng.",
    "SeO₂":"Là selen đioxit, chất rắn trắng, có tính oxi hóa và dùng trong tổng hợp hữu cơ.",
    "H₂Se":"Là hiđro selenua, khí độc, mùi trứng thối rất khó chịu và dễ bị oxi hóa trong không khí.",
    "SeO₃":"Là selen trioxit, chất rắn không bền, có tính oxi hóa mạnh và dễ phân hủy.",
    "HBr":"Là hiđro bromua, khi tan trong nước tạo axit bromhiđric mạnh, có tính ăn mòn cao.",
    "NaBr":"Là natri bromua, muối tinh thể trắng, tan tốt trong nước và dùng trong y học và công nghiệp.",
    "KBr":"Là kali bromua, muối rắn màu trắng, tan trong nước và dùng trong dược phẩm và nhiếp ảnh.",
    "Kr":"Là khí krypton, khí hiếm, rất trơ, không màu, không mùi và hầu như không tham gia phản ứng hóa học.",
    "MnO₂":"Là mangan đioxit, chất rắn màu đen, bền trong điều kiện thường, có tính oxi hóa và thường được dùng làm chất xúc tác trong phản ứng phân hủy H₂O₂ và trong pin khô.",
    "KMnO₄":"Là kali pemanganat, chất rắn màu tím đậm, có tính oxi hóa rất mạnh, dễ tham gia phản ứng oxi hóa-khử và được dùng trong sát trùng, xử lý nước và chuẩn độ.",
    "MnSO₄":"Là mangan(II) sunfat, muối tinh thể màu hồng nhạt, tan trong nước, cung cấp ion Mn²⁺ và dùng trong phân bón và tổng hợp hóa học.",
    "MnCl₂":"Là mangan(II) clorua, muối màu hồng nhạt, tan tốt trong nước, dùng trong công nghiệp hóa chất và mạ điện.",
    "RbCl":"Là rubidi clorua, muối tinh thể trắng, tan tốt trong nước và có tính chất tương tự các muối kim loại kiềm.",
    "RbOH":"Là rubidi hiđroxit, bazơ mạnh, tan tốt trong nước, có tính ăn mòn cao và giải phóng nhiệt khi hòa tan.",
    "Rb₂CO₃":"Là rubidi cacbonat, muối tan trong nước, có tính bazơ yếu và dùng trong nghiên cứu hóa học.",
    "SrO":"Là stronti oxit, chất rắn màu trắng, có tính bazơ mạnh và phản ứng với nước tạo Sr(OH)₂.",
    "SrCl₂":"Là stronti clorua, muối tan trong nước, dùng trong pháo hoa tạo màu đỏ đặc trưng.",
    "SrCO₃":"Là stronti cacbonat, chất rắn ít tan, có trong khoáng strontianit.",
    "Y₂O₃":"Là ytri oxit, chất rắn trắng, bền nhiệt, dùng trong vật liệu gốm và laser.",
    "YCl₃":"Là ytri clorua, muối tan trong nước, dùng trong tổng hợp hóa học.",
    "YF₃":"Là ytri florua, chất rắn bền, ít tan và dùng trong vật liệu quang học.",
    "ZrO₂":"Là zirconi oxit, chất rắn rất bền, chịu nhiệt cao, dùng trong gốm sứ và vật liệu chịu lửa.",
    "ZrCl₄":"Là zirconi clorua, chất rắn dễ bay hơi, bị thủy phân mạnh trong nước.",
    "ZrH₂":"Là zirconi hiđrua, chất rắn không bền, dễ phân hủy và dùng trong nghiên cứu vật liệu.",
    "Nb₂O₅":"Là niobi pentaoxit, chất rắn bền, dùng trong gốm và vật liệu điện tử.",
    "NbCl₅":"Là niobi clorua, chất rắn dễ bay hơi, bị thủy phân mạnh.",
    "NbC":"Là niobi cacbua, chất rắn rất cứng, chịu nhiệt cao.",
    "MoO₃":"Là molypden oxit, chất rắn màu trắng, có tính oxi hóa và dùng làm xúc tác.",
    "MoS₂":"Là molypden đisunfua, chất rắn màu đen, có tính bôi trơn tốt.",
    "MoCl₅":"Là molypden clorua, chất rắn dễ bay hơi và phản ứng mạnh với nước.",
    "TcO₄⁻":"Là ion pertechnetat, dạng oxy hóa cao của technetium, dùng trong y học hạt nhân.",
    "Tc₂O₇":"Là techneti heptaoxit, chất rắn dễ bay hơi và có tính oxi hóa mạnh.",
    "RuO₂":"Là rutheni đioxit, chất rắn dẫn điện tốt, dùng trong điện cực và xúc tác.",
    "RuCl₃":"Là rutheni clorua, muối dùng trong tổng hợp hóa học và xúc tác.",
    "Rh₂O₃":"Là rhodi oxit, chất rắn bền, ít tan và dùng trong xúc tác.",
    "RhCl₃":"Là rhodi clorua, muối dùng trong hóa học và công nghiệp xúc tác.",
    "PdCl₂":"Là palladi clorua, chất rắn dùng làm xúc tác trong phản ứng hữu cơ.",
    "PdO":"Là palladi oxit, chất rắn màu đen, kém bền và dễ bị khử.",
    "AgNO₃":"Là bạc nitrat, muối tan trong nước, có tính oxi hóa và dùng trong y học, phân tích hóa học.",
    "AgCl":"Là bạc clorua, chất rắn trắng, không tan trong nước và nhạy sáng.",
    "Ag₂S":"Là bạc sunfua, chất rắn đen, tạo lớp xỉn màu trên bạc.",
    "CdS":"Là cadmi sunfua, chất rắn màu vàng, dùng làm chất màu nhưng độc.",
    "CdCl₂":"Là cadmi clorua, muối tan trong nước, rất độc và dùng trong mạ điện.",
    "CdO":"Là cadmi oxit, chất rắn màu nâu, độc và dùng trong pin.",
    "In₂O₃":"Là indi oxit, chất rắn trắng, dùng trong màn hình cảm ứng và bán dẫn.",
    "InCl₃":"Là indi clorua, muối dễ tan, dùng trong tổng hợp hóa học.",
    "SnO":"Là thiếc(II) oxit, chất rắn màu đen, có tính khử yếu.",
    "SnO₂":"Là thiếc(IV) oxit, chất rắn trắng, bền và dùng trong gốm, điện tử.",
    "SnCl₂":"Là thiếc(II) clorua, muối tan trong nước, có tính khử.",
    "Sb₂O₃":"Là antimon oxit, chất rắn trắng, độc và dùng trong chất chống cháy.",
    "SbCl₃":"Là antimon clorua, chất lỏng hoặc rắn, bị thủy phân trong nước.",
    "TeO₂":"Là telua đioxit, chất rắn trắng, ít tan và dùng trong vật liệu quang học.",
    "H₂Te":"Là hiđro telua, khí độc, mùi khó chịu và kém bền.",
    "HI":"Là hiđro iodua, trong nước tạo axit mạnh, có tính khử mạnh.",
    "KI":"Là kali iodua, muối tan trong nước, dùng trong y học và bổ sung iot.",
    "I₂O₅":"Là iot pentaoxit, chất rắn, có tính oxi hóa mạnh.",
    "XeF₂":"Là xenon diflorua, hợp chất khí hiếm hiếm gặp, có tính oxi hóa.",
    "XeF₄":"Là xenon tetraflorua, chất rắn, có cấu trúc đặc biệt và phản ứng mạnh.",
    "XeF₆":"Là xenon hexaflorua, chất rắn, có tính oxi hóa rất mạnh.",
    "CsCl":"Là xesi clorua, muối tinh thể trắng, tan rất tốt trong nước và có cấu trúc ion đặc trưng của kim loại kiềm.",
"CsOH":"Là xesi hiđroxit, bazơ rất mạnh, tan hoàn toàn trong nước và có tính ăn mòn cao.",
"Cs₂CO₃":"Là xesi cacbonat, muối trắng, tan trong nước và có tính bazơ yếu trong dung dịch.",

"BaSO₄":"Là bari sunfat, chất rắn trắng, không tan trong nước, rất bền và được dùng trong chụp X-quang hệ tiêu hóa.",
"BaCl₂":"Là bari clorua, muối tan trong nước, độc và được dùng trong phân tích ion sunfat.",
"BaCO₃":"Là bari cacbonat, chất rắn trắng, ít tan trong nước và dễ phân hủy khi nung.",

"HfO₂":"Là hafni đioxit, chất rắn rất bền nhiệt, dùng trong vật liệu gốm và điện tử cao cấp.",
"HfCl₄":"Là hafni tetraclorua, chất rắn dễ bay hơi, bị thủy phân mạnh trong nước.",

"Ta₂O₅":"Là tantan pentaoxit, chất rắn rất bền, có tính cách điện tốt và dùng trong tụ điện.",
"TaCl₅":"Là tantan clorua, chất rắn dễ bay hơi, phản ứng mạnh với nước.",

"WO₃":"Là vonfram trioxit, chất rắn màu vàng, có tính oxi hóa yếu và dùng trong gốm, cảm biến.",
"WC":"Là vonfram cacbua, chất rắn cực cứng, chịu mài mòn cao và dùng trong dụng cụ cắt.",

"Re₂O₇":"Là rheni heptaoxit, chất rắn dễ bay hơi, có tính oxi hóa mạnh.",

"OsO₄":"Là osmi tetroxit, chất lỏng bay hơi, cực độc và có tính oxi hóa rất mạnh.",

"Ir₂O₃":"Là iridi oxit, chất rắn bền, ít phản ứng và có tính ổn định cao.",

"PtO₂":"Là bạch kim oxit, chất rắn, kém bền và dễ bị khử về Pt kim loại.",

"AuCl₃":"Là vàng(III) clorua, hợp chất vàng có tính oxi hóa, tan trong nước cường toan.",

"HgO":"Là thủy ngân oxit, chất rắn màu đỏ hoặc vàng, dễ bị phân hủy khi đun nóng.",
"HgCl₂":"Là thủy ngân clorua, chất rắn trắng, cực độc và tan trong nước.",

"Tl₂O₃":"Là thali oxit, chất rắn, độc và có tính oxi hóa yếu.",
"TlCl":"Là thali clorua, muối tan trong nước, độc và dễ bị khử.",

"PbO":"Là chì oxit, chất rắn vàng hoặc đỏ, có tính lưỡng tính yếu và dùng trong công nghiệp pin.",
"PbSO₄":"Là chì sunfat, chất rắn trắng, ít tan và hình thành trong pin chì-axit.",
"PbCl₂":"Là chì clorua, chất rắn trắng, ít tan trong nước lạnh.",

"Bi₂O₃":"Là bismut oxit, chất rắn vàng, ít độc và dùng trong gốm và dược phẩm.",
"BiCl₃":"Là bismut clorua, chất rắn dễ thủy phân trong nước.",

"PoO₂":"Là poloni đioxit, hợp chất phóng xạ, rất độc và ít nghiên cứu do tính không ổn định.",

"At₂":"Là astatin phân tử (giả định), rất hiếm và không bền, chủ yếu tồn tại dạng phóng xạ ngắn hạn.",

"Rn":"Là radon, khí hiếm phóng xạ, không màu, không mùi và không tạo hợp chất ổn định trong điều kiện thường.",
"La₂O₃":"Là lantan oxit, chất rắn màu trắng, có tính bazơ yếu và dễ phản ứng với axit, dùng trong gốm và vật liệu quang học.",
"LaCl₃":"Là lantan clorua, muối tan trong nước, dùng trong xúc tác và tổng hợp hóa học.",

"CeO₂":"Là xeri đioxit, chất rắn màu trắng vàng, có tính oxi hóa - khử linh hoạt và dùng trong xúc tác ô tô và đánh bóng kính.",
"CeCl₃":"Là xeri clorua, muối tan trong nước, dùng trong tổng hợp hữu cơ và xúc tác.",

"Pr₂O₃":"Là praseodymi oxit, chất rắn màu xanh lục nhạt, dùng trong gốm và vật liệu quang học.",
"PrCl₃":"Là praseodymi clorua, muối tan trong nước, dùng trong nghiên cứu và công nghệ vật liệu.",

"Nd₂O₃":"Là neodymi oxit, chất rắn màu xanh lam, quan trọng trong sản xuất nam châm vĩnh cửu cực mạnh.",
"NdCl₃":"Là neodymi clorua, muối tan trong nước, dùng trong tổng hợp hóa học.",

"Pm₂O₃":"Là prometi oxit, hợp chất phóng xạ, rất hiếm và không bền trong tự nhiên.",

"Sm₂O₃":"Là samari oxit, chất rắn màu vàng nhạt, có tính từ và dùng trong vật liệu từ tính.",
"SmCl₃":"Là samari clorua, muối tan trong nước, dùng trong nghiên cứu vật liệu.",

"Eu₂O₃":"Là europi oxit, chất rắn màu trắng hồng, có tính phát quang mạnh, dùng trong màn hình và đèn LED.",
"EuCl₃":"Là europi clorua, muối tan trong nước, dùng trong vật liệu phát quang.",

"Gd₂O₃":"Là gadolini oxit, chất rắn trắng, có tính từ mạnh và dùng trong vật liệu y học và MRI.",
"GdCl₃":"Là gadolini clorua, muối tan trong nước, dùng trong y học hạt nhân.",

"Tb₂O₃":"Là terbi oxit, chất rắn màu trắng, có tính phát quang mạnh và dùng trong màn hình.",
"TbCl₃":"Là terbi clorua, muối tan trong nước, dùng trong công nghệ vật liệu.",

"Dy₂O₃":"Là dysprosi oxit, chất rắn màu trắng, chịu từ trường mạnh và nhiệt độ cao.",
"DyCl₃":"Là dysprosi clorua, muối tan trong nước, dùng trong nam châm công suất cao.",

"Ho₂O₃":"Là holmi oxit, chất rắn màu vàng nhạt, có từ tính mạnh và dùng trong laser.",
"HoCl₃":"Là holmi clorua, muối tan trong nước, dùng trong nghiên cứu vật liệu.",

"Er₂O₃":"Là erbi oxit, chất rắn hồng, dùng trong sợi quang và laser công suất cao.",
"ErCl₃":"Là erbi clorua, muối tan trong nước, dùng trong công nghệ quang học.",

"Tm₂O₃":"Là thuli oxit, chất rắn màu xanh nhạt, rất hiếm và dùng trong laser y học.",
"TmCl₃":"Là thuli clorua, muối tan trong nước, dùng trong nghiên cứu khoa học.",

"Yb₂O₃":"Là ytterbi oxit, chất rắn trắng, dùng trong laser và nghiên cứu lượng tử.",
"YbCl₃":"Là ytterbi clorua, muối tan trong nước, dùng trong công nghệ vật liệu.",

"Lu₂O₃":"Là luteti oxit, chất rắn bền, dùng trong y học hạt nhân và vật liệu tiên tiến.",
"LuCl₃":"Là luteti clorua, muối tan trong nước, dùng trong tổng hợp hóa học.",
"Ac₂O₃":"Là actini oxit, chất rắn phóng xạ, có tính bazơ yếu và phản ứng với axit tạo muối actinium.",
"AcCl₃":"Là actini clorua, muối phóng xạ, tan trong nước và dễ thủy phân.",

"ThO₂":"Là thori đioxit, chất rắn rất bền nhiệt, dùng làm nhiên liệu hạt nhân và vật liệu chịu nhiệt.",
"ThCl₄":"Là thori tetraclorua, chất rắn dễ bay hơi, bị thủy phân mạnh trong nước.",

"Pa₂O₅":"Là protactini pentaoxit, hợp chất phóng xạ, ít bền và chỉ dùng trong nghiên cứu.",

"UO₂":"Là urani đioxit, chất rắn đen, là nhiên liệu hạt nhân quan trọng trong lò phản ứng.",
"UF₆":"Là urani hexaflorua, chất dễ bay hơi, dùng trong làm giàu urani.",

"NpO₂":"Là neptuni đioxit, chất rắn phóng xạ, dùng trong nghiên cứu hạt nhân.",

"PuO₂":"Là plutoni đioxit, chất rắn phóng xạ mạnh, dùng trong nhiên liệu hạt nhân.",

"AmO₂":"Là americi đioxit, chất rắn phóng xạ, dùng trong thiết bị phát hiện khói.",

"CmO₂":"Là curi đioxit, chất rắn phóng xạ, dùng trong nguồn nhiệt và nghiên cứu.",

"Bk":"Là berkelini kim loại, rất hiếm và phóng xạ mạnh, gần như không tạo hợp chất bền.",

"Cf":"Là californi kim loại, có khả năng phát neutron mạnh, dùng trong dò mìn.",

"Es":"Là einsteini, nguyên tố phóng xạ nhân tạo, cực kỳ không bền.",

"Fm":"Là fermini, nguyên tố nhân tạo, chỉ tồn tại trong thời gian rất ngắn.",

"Md":"Là mendelevi, nguyên tố siêu nặng, dùng trong nghiên cứu hạt nhân.",

"No":"Là nobeli, nguyên tố nhân tạo phóng xạ mạnh, không bền.",

"Lr":"Là lawrenci, nguyên tố cuối dãy actinide, cực kỳ không ổn định."
}



const reactionsDetail = {
    "2H₂ + O₂ → 2H₂O" : "Cháy mạnh, tỏa nhiều nhiệt, dễ gây nổ khi trộn với không khí, dùng làm nhiên liệu (tên lửa, pin nhiên liệu).",
    "H₂ + Cl₂ → 2HCl" : "Phản ứng nhanh dưới ánh sáng, có thể nổ, tạo HCl, dùng sản xuất axit HCl.",
    "N₂ + 3H₂ ⇌ 2NH₃" : "Xảy ra ở nhiệt độ, áp suất cao, có xúc tác Fe, dùng sản xuất NH₃ (phân bón).",
    "2Li + 2H₂O → 2LiOH + H₂" : "Phản ứng khá chậm (so với Na, K), tỏa nhiệt, tạo dung dịch bazơ LiOH và khí H₂; Li nổi trên nước và sủi bọt khí.",
    "4Li + O₂ → 2Li₂O" : "Cháy trong oxi, tỏa nhiều nhiệt, phát sáng màu đỏ thẫm, tạo oxit Li₂O; xảy ra khi đun nóng hoặc trong không khí.",
    "6Li + N₂ → 2Li₃N" : "Phản ứng trực tiếp với N₂ ngay ở điều kiện thường, tạo Li₃N; là tính chất đặc biệt của Li so với các kim loại kiềm khác.",
    "2Be + O₂ → 2BeO" : "Phản ứng khi đun nóng, tỏa nhiệt, tạo BeO là chất rắn bền, có tính lưỡng tính.",
    "Be + 2HCl → BeCl₂ + H₂" : "Phản ứng với axit giải phóng khí H₂, tạo muối tan BeCl₂.",
    "Be + Cl₂ → BeCl₂" : "Phản ứng khi đun nóng, cháy tạo muối BeCl₂ dạng rắn, thể hiện khả năng phản ứng trực tiếp với halogen và tính chất kim loại của Be.",
    "4B + 3O₂ → 2B₂O₃" : "Boron cháy trong oxi khi đun nóng, tỏa nhiều nhiệt tạo B₂O₃ là oxit axit, chất rắn thủy tinh dễ hút ẩm.",
    "B₂O₃ + 3H₂O → 2H₃BO₃" : "B₂O₃ phản ứng với nước tạo axit boric H₃BO₃, là axit yếu, tan ít trong nước và có tính sát khuẩn nhẹ.",
    "2B + 3Cl₂ → 2BCl₃" : "Boron phản ứng trực tiếp với clo khi đun nóng tạo BCl₃, dễ bay hơi và bị thủy phân mạnh trong nước.",
    "C + O₂ → CO₂":"Cacbon cháy hoàn toàn trong oxi khi đủ lượng, tỏa nhiều nhiệt và tạo khí CO₂ là sản phẩm oxi hóa bền.",
    "2C + O₂ → 2CO":"Cacbon cháy không hoàn toàn trong điều kiện thiếu oxi, tạo khí CO là chất độc, không màu, không mùi.",
    "C + 2H₂ → CH₄":"Cacbon phản ứng với hiđro ở nhiệt độ và áp suất cao có xúc tác, tạo metan CH₄ là hiđrocacbon đơn giản nhất.",
    "N₂ + 3H₂ → 2NH₃":"Nitơ phản ứng với hiđro ở nhiệt độ, áp suất cao và có xúc tác Fe tạo amoniac NH₃ trong quá trình Haber.",
    "N₂ + O₂ → 2NO":"Nitơ phản ứng với oxi ở nhiệt độ rất cao (tia sét hoặc buồng đốt) tạo NO.",
    "4NH₃ + 5O₂ → 4NO + 6H₂O":"Amoniac bị oxi hóa ở nhiệt độ cao có xúc tác Pt tạo NO và nước trong quá trình sản xuất HNO₃.",
    "2H₂ + O₂ → 2H₂O":"Hiđro cháy trong oxi, tỏa nhiều nhiệt và tạo nước là phản ứng tỏa năng lượng mạnh.",
    "C + O₂ → CO₂":"Cacbon cháy hoàn toàn trong oxi, tỏa nhiều nhiệt và tạo CO₂ là sản phẩm oxi hóa bền.",
    "2Mg + O₂ → 2MgO":"Magie cháy sáng trong oxi, tỏa nhiệt mạnh tạo MgO là chất rắn màu trắng.",
    "H₂ + F₂ → 2HF":"Hiđro phản ứng trực tiếp với flo ngay ở điều kiện thường hoặc ánh sáng, tạo HF và tỏa năng lượng mạnh.",
    "2Na + F₂ → 2NaF":"Natri phản ứng mãnh liệt với flo, tạo muối NaF và tỏa nhiều nhiệt, có thể gây cháy sáng.",
    "2Na + 2H₂O → 2NaOH + H₂":"Natri phản ứng mãnh liệt với nước, tỏa nhiệt mạnh, tạo dung dịch bazơ NaOH và khí H₂ dễ cháy.",
    "2Na + Cl₂ → 2NaCl":"Natri phản ứng trực tiếp với clo, cháy sáng tạo muối NaCl và tỏa nhiều nhiệt.",
    "2Mg + O₂ → 2MgO":"Magie cháy sáng trong oxi, tỏa nhiệt mạnh tạo MgO là chất rắn màu trắng.",
    "Mg + 2HCl → MgCl₂ + H₂":"Magie phản ứng với axit giải phóng khí H₂ và tạo muối MgCl₂ tan trong nước.",
    "4Al + 3O₂ → 2Al₂O₃":"Nhôm cháy trong oxi khi đun nóng, tỏa nhiều nhiệt tạo lớp Al₂O₃ bền bảo vệ bề mặt kim loại.",
    "2Al + 6HCl → 2AlCl₃ + 3H₂":"Nhôm phản ứng với axit giải phóng khí H₂ và tạo muối AlCl₃ tan trong nước.",
    "Si + O₂ → SiO₂":"Silic cháy trong oxi khi đun nóng, tỏa nhiệt tạo SiO₂ là chất rắn bền.",
    "Si + 2Cl₂ → SiCl₄":"Silic phản ứng với clo khi đun nóng tạo SiCl₄ là chất lỏng dễ bay hơi.",
    "4P + 5O₂ → 2P₂O₅":"Photpho cháy trong oxi, tỏa nhiều nhiệt tạo P₂O₅ là oxit axit mạnh.",
    "P₄ + 6Cl₂ → 4PCl₃":"Photpho phản ứng với clo tạo PCl₃, chất lỏng độc và dễ bị oxi hóa tiếp.",
    "S + O₂ → SO₂":"Lưu huỳnh cháy trong oxi tạo SO₂, tỏa nhiệt và có ngọn lửa màu xanh.",
    "2H₂ + S → H₂S":"Hiđro phản ứng với lưu huỳnh ở nhiệt độ cao tạo khí H₂S có mùi trứng thối.",
    "2S + 3O₂ → 2SO₃":"Lưu huỳnh bị oxi hóa mạnh trong điều kiện thích hợp tạo SO₃ là oxit axit mạnh.",
    "H₂ + Cl₂ → 2HCl":"Hiđro phản ứng trực tiếp với clo dưới ánh sáng hoặc nhiệt độ tạo khí HCl, phản ứng tỏa năng lượng mạnh.",
    "2Na + Cl₂ → 2NaCl":"Natri phản ứng mãnh liệt với clo, tạo muối NaCl và tỏa nhiều nhiệt, có thể cháy sáng.",
    "2K + 2H₂O → 2KOH + H₂":"Kali phản ứng rất mạnh với nước, tỏa nhiệt và khí H₂ dễ cháy, tạo dung dịch KOH bazơ mạnh.",
    "2K + Cl₂ → 2KCl":"Kali phản ứng mãnh liệt với clo, tạo muối KCl và tỏa nhiều nhiệt, có thể phát sáng.",
    "Ca + 2H₂O → Ca(OH)₂ + H₂":"Canxi phản ứng với nước, tỏa nhiệt và tạo dung dịch bazơ Ca(OH)₂ cùng khí H₂.",
    "2Ca + O₂ → 2CaO":"Canxi cháy trong oxi khi đun nóng, tỏa nhiệt tạo CaO là chất rắn màu trắng.",
    "4Sc + 3O₂ → 2Sc₂O₃":"Scandium cháy trong oxi khi đun nóng, tỏa nhiệt tạo Sc₂O₃ là oxit bền.",
    "2Sc + 6HCl → 2ScCl₃ + 3H₂":"Scandium phản ứng với axit, giải phóng khí H₂ và tạo muối ScCl₃ tan trong nước.",
    "Ti + O₂ → TiO₂":"Titan phản ứng với oxi khi đun nóng, tạo TiO₂ là oxit bền, bảo vệ bề mặt kim loại.",
    "Ti + 2Cl₂ → TiCl₄":"Titan phản ứng trực tiếp với clo tạo TiCl₄ là chất lỏng dễ bay hơi và bị thủy phân mạnh.",
    "4V + 5O₂ → 2V₂O₅":"Vanadi cháy trong oxi khi đun nóng, tạo V₂O₅ là oxit có tính oxi hóa mạnh.",
    "2V + 5Cl₂ → 2VCl₅":"Vanadi phản ứng với clo tạo VCl₅, hợp chất dễ bay hơi và không bền trong điều kiện thường.",
    "4Cr + 3O₂ → 2Cr₂O₃":"Crom cháy trong oxi khi đun nóng, tạo Cr₂O₃ là lớp oxit bền bảo vệ bề mặt kim loại.",
    "2Cr + 6HCl → 2CrCl₃ + 3H₂":"Crom phản ứng với axit giải phóng khí H₂ và tạo muối CrCl₃ tan trong nước.",
    "4Mn + 3O₂ → 2Mn₂O₃":"Mangan bị oxi hóa trong không khí khi đun nóng, tạo oxit mangan(III) là chất rắn bền.",
    "2KMnO₄ → K₂MnO₄ + MnO₂ + O₂":"Kali pemanganat phân hủy khi đun nóng, giải phóng khí oxi và tạo các sản phẩm mangan khác nhau.",
    "4Fe + 3O₂ → 2Fe₂O₃":"Sắt bị oxi hóa trong không khí ẩm, tạo Fe₂O₃ là thành phần chính của gỉ sắt.",
    "Fe + 2HCl → FeCl₂ + H₂":"Sắt phản ứng với axit clohiđric, giải phóng khí hiđro và tạo muối sắt(II) clorua.",
    "2Co + O₂ → 2CoO":"Coban cháy trong oxi khi đun nóng, tạo CoO là oxit bền màu xám xanh.",
    "Co + 2HCl → CoCl₂ + H₂":"Coban phản ứng với axit, giải phóng khí hiđro và tạo muối coban(II) clorua.",
    "2Ni + O₂ → 2NiO":"Niken bị oxi hóa trong oxi, tạo NiO là oxit màu xanh lục.",
    "Ni + 2HCl → NiCl₂ + H₂":"Niken phản ứng với axit mạnh, tạo muối niken(II) clorua và khí hiđro.",
    "2Cu + O₂ → 2CuO":"Đồng bị oxi hóa khi đun nóng trong không khí, tạo CuO màu đen.",
    "Cu + 2HCl → CuCl₂ + H₂":"Đồng phản ứng với axit (điều kiện thích hợp), tạo muối đồng(II) clorua.",
    "Zn + 2HCl → ZnCl₂ + H₂":"Kẽm phản ứng mạnh với axit, giải phóng khí hiđro và tạo muối kẽm clorua.",
    "2Zn + O₂ → 2ZnO":"Kẽm cháy trong oxi, tạo ZnO là chất rắn màu trắng.",
    "4Ga + 3O₂ → 2Ga₂O₃":"Gali bị oxi hóa trong oxi khi đun nóng, tạo Ga₂O₃ bền nhiệt.",
    "2Ga + 3Cl₂ → 2GaCl₃":"Gali phản ứng với clo, tạo muối gali clorua dễ bay hơi.",
    "Ge + O₂ → GeO₂":"Germani bị oxi hóa trong oxi, tạo GeO₂ là oxit bền.",
    "Ge + 2Cl₂ → GeCl₄":"Germani phản ứng với clo, tạo GeCl₄ dễ bay hơi và bị thủy phân.",
    "4As + 3O₂ → 2As₂O₃":"Asen bị oxi hóa trong oxi, tạo As₂O₃ là chất độc.",
    "2As + 3Cl₂ → 2AsCl₃":"Asen phản ứng với clo, tạo hợp chất clorua của asen.",
    "Se + O₂ → SeO₂":"Selen bị oxi hóa trong oxi, tạo SeO₂ là oxit bền.",
    "H₂ + Se → H₂Se":"Hiđro phản ứng với selen khi đun nóng, tạo khí H₂Se độc.",
    "H₂ + Br₂ → 2HBr":"Hiđro phản ứng với brom dưới ánh sáng, tạo khí HBr.",
    "2Na + Br₂ → 2NaBr":"Natri phản ứng mạnh với brom, tạo muối natri bromua và tỏa nhiều nhiệt.",
    "Mn + O₂ → MnO₂":"Mangan bị oxi hóa trong oxi khi đun nóng, tạo MnO₂ là oxit bền của mangan.",
    "2KMnO₄ → K₂MnO₄ + MnO₂ + O₂":"Kali pemanganat phân hủy khi đun nóng, tạo manganat, mangan đioxit và giải phóng khí oxi.",
    "2Rb + 2H₂O → 2RbOH + H₂":"Rubidi phản ứng rất mạnh với nước, tỏa nhiều nhiệt và giải phóng khí hiđro dễ cháy, tạo dung dịch bazơ mạnh RbOH.",
"2Rb + Cl₂ → 2RbCl":"Rubidi cháy mạnh trong clo, tạo muối RbCl và tỏa nhiều năng lượng.",

"2Sr + O₂ → 2SrO":"Stronti cháy trong oxi khi đun nóng, tạo SrO là oxit bazơ màu trắng.",
"Sr + 2H₂O → Sr(OH)₂ + H₂":"Stronti phản ứng với nước, tạo dung dịch bazơ Sr(OH)₂ và khí hiđro.",

"4Y + 3O₂ → 2Y₂O₃":"Ytri bị oxi hóa trong oxi khi đun nóng, tạo Y₂O₃ là oxit bền nhiệt.",
"2Y + 6HCl → 2YCl₃ + 3H₂":"Ytri phản ứng với axit, giải phóng khí hiđro và tạo muối YCl₃.",

"Zr + O₂ → ZrO₂":"Zirconi bị oxi hóa trong oxi tạo ZrO₂ là oxit rất bền, chịu nhiệt cao.",
"Zr + 2Cl₂ → ZrCl₄":"Zirconi phản ứng với clo, tạo ZrCl₄ là chất dễ bay hơi và bị thủy phân mạnh.",

"4Nb + 5O₂ → 2Nb₂O₅":"Niobi bị oxi hóa trong oxi tạo Nb₂O₅ là oxit bền.",
"2Nb + 5Cl₂ → 2NbCl₅":"Niobi phản ứng với clo, tạo NbCl₅ dễ bay hơi và phản ứng mạnh với nước.",

"2Mo + 3O₂ → 2MoO₃":"Molypden bị oxi hóa trong oxi tạo MoO₃ là oxit có tính oxi hóa.",
"Mo + 2Cl₂ → MoCl₄":"Molypden phản ứng với clo tạo muối clorua trong điều kiện thích hợp.",

"Tc + O₂ → Tc₂O₇":"Techneti bị oxi hóa trong oxi tạo Tc₂O₇ là oxit bay hơi và có tính oxi hóa mạnh.",

"Ru + O₂ → RuO₂":"Rutheni bị oxi hóa tạo RuO₂, chất rắn dẫn điện và bền.",
"4Ru + 3O₂ → 2Ru₂O₃":"Rutheni có thể tạo nhiều oxit tùy điều kiện oxi hóa.",

"4Rh + 3O₂ → 2Rh₂O₃":"Rhodini bị oxi hóa trong oxi tạo Rh₂O₃ là oxit bền.",

"2Pd + O₂ → 2PdO":"Palladi bị oxi hóa tạo PdO là oxit không bền và dễ bị khử.",

"2Ag + S → Ag₂S":"Bạc phản ứng với lưu huỳnh trong không khí tạo Ag₂S gây xỉn màu bề mặt.",
"2Ag + Cl₂ → 2AgCl":"Bạc phản ứng với clo tạo AgCl là chất kết tủa trắng nhạy sáng.",

"2Cd + O₂ → 2CdO":"Cadmi cháy trong oxi tạo CdO là oxit màu nâu và độc.",
"Cd + 2HCl → CdCl₂ + H₂":"Cadmi phản ứng với axit giải phóng khí hiđro và tạo muối CdCl₂.",

"4In + 3O₂ → 2In₂O₃":"Indi bị oxi hóa trong oxi tạo In₂O₃ là oxit bền.",

"Sn + O₂ → SnO₂":"Thiếc bị oxi hóa trong oxi tạo SnO₂ là oxit bền và dùng nhiều trong công nghiệp.",
"Sn + 2HCl → SnCl₂ + H₂":"Thiếc phản ứng với axit giải phóng khí hiđro và tạo muối SnCl₂.",

"4Sb + 3O₂ → 2Sb₂O₃":"Antimon bị oxi hóa tạo Sb₂O₃ là oxit độc và dùng trong chống cháy.",

"Te + O₂ → TeO₂":"Telua bị oxi hóa trong oxi tạo TeO₂ là oxit bền.",

"H₂ + I₂ → 2HI":"Hiđro phản ứng với iot khi đun nóng tạo HI là axit mạnh trong dung dịch.",

"Xe + F₂ → XeF₂":"Xenon phản ứng với flo trong điều kiện đặc biệt tạo XeF₂, hợp chất khí hiếm hiếm gặp và có tính oxi hóa.",
"2Cs + 2H₂O → 2CsOH + H₂":"Xesi phản ứng cực mạnh với nước, tỏa nhiệt lớn và tạo dung dịch bazơ mạnh CsOH cùng khí hiđro dễ cháy.",
"2Cs + Cl₂ → 2CsCl":"Xesi cháy trong khí clo, phản ứng mãnh liệt tạo muối CsCl và giải phóng nhiều năng lượng.",

"Ba + 2H₂O → Ba(OH)₂ + H₂":"Bari phản ứng với nước tạo dung dịch bazơ Ba(OH)₂ và khí hiđro, phản ứng xảy ra dễ dàng hơn so với các kim loại kiềm thổ nhẹ hơn.",
"2Ba + O₂ → 2BaO":"Bari bị oxi hóa trong oxi khi đun nóng tạo BaO là oxit bazơ màu trắng.",

"Hf + O₂ → HfO₂":"Hafni bị oxi hóa trong oxi tạo HfO₂, oxit rất bền nhiệt và chống ăn mòn cao.",
"Hf + 2Cl₂ → HfCl₄":"Hafni phản ứng với clo tạo HfCl₄, hợp chất dễ bay hơi và bị thủy phân trong nước.",

"4Ta + 5O₂ → 2Ta₂O₅":"Tantan bị oxi hóa tạo Ta₂O₅, oxit rất bền và có tính cách điện tốt.",
"2Ta + 5Cl₂ → 2TaCl₅":"Tantan phản ứng với clo tạo TaCl₅, hợp chất dễ bay hơi và phản ứng mạnh với nước.",

"W + O₂ → WO₃":"Vonfram bị oxi hóa ở nhiệt độ cao tạo WO₃, oxit bền và có tính oxi hóa yếu.",
"W + C → WC":"Vonfram phản ứng với cacbon tạo WC, hợp chất rất cứng dùng trong dụng cụ cắt gọt.",

"4Re + 7O₂ → 2Re₂O₇":"Rheni bị oxi hóa tạo Re₂O₇, oxit dễ bay hơi và có tính oxi hóa mạnh.",

"Os + O₂ → OsO₄":"Osmi bị oxi hóa tạo OsO₄, hợp chất bay hơi, rất độc và có tính oxi hóa mạnh.",

"4Ir + 3O₂ → 2Ir₂O₃":"Iridi bị oxi hóa tạo oxit iridi, phản ứng xảy ra khó do kim loại rất bền.",

"Pt + O₂ → PtO₂":"Bạch kim có thể bị oxi hóa trong điều kiện đặc biệt tạo PtO₂, nhưng rất khó xảy ra do tính trơ cao.",

"Au + Cl₂ → AuCl₃":"Vàng phản ứng với clo (hoặc nước cường toan) tạo AuCl₃, vì vàng rất trơ nên phản ứng khó xảy ra.",

"2Hg + O₂ → 2HgO":"Thủy ngân bị oxi hóa khi đun nóng tạo HgO, chất rắn đỏ hoặc vàng nhạt.",

"4Tl + 3O₂ → 2Tl₂O₃":"Thali bị oxi hóa trong oxi tạo oxit Tl₂O₃, phản ứng xảy ra nhưng kim loại rất độc.",

"2Pb + O₂ → 2PbO":"Chì bị oxi hóa trong oxi tạo PbO, oxit có tính lưỡng tính yếu.",

"4Bi + 3O₂ → 2Bi₂O₃":"Bismut bị oxi hóa tạo Bi₂O₃, oxit bền và ít độc hơn nhiều kim loại nặng khác.",

"Po + O₂ → PoO₂":"Poloni bị oxi hóa tạo PoO₂, nhưng phản ứng ít được nghiên cứu do tính phóng xạ cực mạnh.",

"Rn → (không phản ứng điển hình)":"Radon là khí hiếm phóng xạ, rất trơ hóa học nên hầu như không tham gia phản ứng trong điều kiện thường.",
"4La + 3O₂ → 2La₂O₃":"Lantan bị oxi hóa trong không khí tạo oxit La₂O₃ là chất rắn bền.",
"La + 3HCl → LaCl₃ + 3/2 H₂":"Lantan phản ứng với axit tạo muối clorua và khí hiđro.",

"4Ce + 3O₂ → 2Ce₂O₃":"Xeri bị oxi hóa trong oxi tạo Ce₂O₃, có tính oxi hóa - khử linh hoạt.",
"Ce + 3HCl → CeCl₃ + 3/2 H₂":"Xeri phản ứng với axit tạo muối và khí hiđro.",

"4Pr + 3O₂ → 2Pr₂O₃":"Prazeodymi bị oxi hóa tạo oxit Pr₂O₃ màu xanh lục nhạt.",

"4Nd + 3O₂ → 2Nd₂O₃":"Neodymi bị oxi hóa trong không khí tạo oxit bền Nd₂O₃.",

"Pm → (không phản ứng bền)":"Prometi là nguyên tố phóng xạ, không có phản ứng hóa học ổn định điển hình.",

"4Sm + 3O₂ → 2Sm₂O₃":"Samari bị oxi hóa tạo oxit Sm₂O₃ có tính từ mạnh.",

"4Eu + 3O₂ → 2Eu₂O₃":"Europi bị oxi hóa tạo oxit Eu₂O₃ có tính phát quang.",

"4Gd + 3O₂ → 2Gd₂O₃":"Gadolini bị oxi hóa tạo oxit Gd₂O₃ dùng trong y học và vật liệu từ.",

"4Tb + 3O₂ → 2Tb₂O₃":"Terbi bị oxi hóa tạo oxit Tb₂O₃ có tính phát quang.",

"4Dy + 3O₂ → 2Dy₂O₃":"Dysprosi bị oxi hóa tạo oxit Dy₂O₃ chịu từ trường mạnh.",

"4Ho + 3O₂ → 2Ho₂O₃":"Holmi bị oxi hóa tạo oxit Ho₂O₃ có từ tính cao.",

"4Er + 3O₂ → 2Er₂O₃":"Erbi bị oxi hóa tạo oxit Er₂O₃ dùng trong sợi quang.",

"4Tm + 3O₂ → 2Tm₂O₃":"Thuli bị oxi hóa tạo oxit Tm₂O₃ rất hiếm.",

"4Yb + 3O₂ → 2Yb₂O₃":"Ytterbi bị oxi hóa tạo oxit Yb₂O₃.",

"4Lu + 3O₂ → 2Lu₂O₃":"Luteti bị oxi hóa tạo oxit Lu₂O₃ là oxit bền nhất dãy.",
"4Ac + 3O₂ → 2Ac₂O₃":"Actini bị oxi hóa trong không khí tạo oxit Ac₂O₃ là chất rắn phóng xạ.",
"Ac + 3HCl → AcCl₃ + 3/2 H₂":"Actini phản ứng với axit giải phóng khí hiđro và tạo muối clorua.",

"Th + O₂ → ThO₂":"Thori bị oxi hóa tạo ThO₂ rất bền nhiệt, dùng trong vật liệu hạt nhân.",

"U + O₂ → UO₂":"Urani bị oxi hóa tạo UO₂ là dạng nhiên liệu hạt nhân quan trọng.",
"U + 3F₂ → UF₆":"Urani phản ứng với flo tạo UF₆ dễ bay hơi dùng trong làm giàu urani.",

"Np + O₂ → NpO₂":"Neptuni bị oxi hóa tạo oxit NpO₂ trong điều kiện đặc biệt.",

"Pu + O₂ → PuO₂":"Plutoni bị oxi hóa tạo PuO₂, hợp chất quan trọng trong nhiên liệu hạt nhân.",

"Am → (không phản ứng bền)":"Americi chủ yếu tồn tại dạng phóng xạ, phản ứng hóa học hạn chế.",

"Cm → (không phản ứng rõ)":"Curi là nguyên tố phóng xạ nhân tạo, phản ứng hóa học không ổn định.",

"Bk → (không phản ứng điển hình)":"Berkeli chỉ tồn tại lượng rất nhỏ, không có phản ứng hóa học phổ biến.",

"Cf → (phát neutron)":"Californi chủ yếu phân rã phóng xạ, không có phản ứng hóa học thông thường.",

"Es → (phân rã phóng xạ)":"Einsteini không bền, chỉ tồn tại trong thí nghiệm hạt nhân.",

"Fm → (phân rã phóng xạ)":"Fermini cực kỳ không bền, không có phản ứng hóa học đáng kể.",

"Md → (phân rã phóng xạ)":"Mendelevi chỉ được tạo ra nhân tạo trong thí nghiệm.",

"No → (phân rã phóng xạ)":"Nobeli không ổn định, tồn tại rất ngắn.",

"Lr → (phân rã phóng xạ)":"Lawrenci là nguyên tố tổng hợp, không có phản ứng hóa học bền."
}